### ISSUE TITLE
新的 unblock [DNS] 伺服器測試進行中

### ISSUE THREAD

**Issue by karlcheong** [zhuzhuor/Unblock-Youku#112]
#### **回報問題時請詳細描述問題, 附上你的地區/ISP/使用的平台/網站, 不然將有可能遭忽略!**
-----
由#106 在家用路由中應用unblock服務的一些想法 
現在由@zhuzhuor和我建立了一個新的unblock伺服器

以下借用一下zhuzhuor的WIKI內容

-----

# **注意，使用本服務代表您同意以下條款**

1. 相對於 Chrome 擴展程式，這種代理伺服器的模式會有安全隱患。如果代理伺服器被黑，則可能造成個人隱私洩漏或財產損失。

2. 因為技術上的原因，這種代理模式在功能，連接可用性及反應速度可能會受各種因素影響。

# **程式作者及伺服器提供者對任何可能的後果概不負責。**

#### 測試進行時有問題可以在這里回復

----

## DNS代理比現在yo.uku.im PAC代理多了以下功能：

1. DNS+反向代理: 就是類似unblock-us那樣，利用DNS+反向代理解封國家限制，只是針對的是中國而不是美國, 用戶可以通過修改DNS設定連接到伺服器。 For reference: https://trafficserver.apache.org/docs/trunk/admin/reverse-proxy-http-redirects/ 。
2.  PAC代理，DNS開放非常規端口給位於透明代理/防火牆後的用戶, 以解決類似 #104 問題
3.  伺服器接入HE的IPv6隧道(記得某個帖中有人問IPv6的需求) 
4.  破解部分Apps 廣告,影片下載限制 (只限使用DNS並/或自行修改host,pac) (不保證能用)
5.  OpenDNS / Norton DNS 過濾各種不良網頁。

．．．請提出你的建議

### 目前支持的OS
支持PAC的各種瀏覽器, iOS Apps, Android Apps

       由於開通了反向代理服務, Android也可以通過這個服務unblock youku 了喔!
       暫時測試支持的有(以支持Apps為主)
       Apps: youku, tudou, iqiyi, letv, tencent video, sohu, baidu music, qq music, kuwo, kugou, duomi, ttpod.....
       Webpage: youku, tudou, iqiyi, letv, tencent video, sohu, baidu music

### 設定值：
PAC地址：http://dns.umbridges2014.com/proxy.pac
非常規端口(8000) PAC地址：http://dns.umbridges2014.com/altproxy.pac
DNS IPv4地址：192.241.222.103
DNS IPv6地址：2001:470:832e:1024:6969:5269::1
DNS端口： 53,5353 udp tcp 
轉發模式後台： http://berryphp.ap01.aws.af.cm/digito.php

桌面電腦, iOS: 請看 http://ub.uku.im/proxy 把上面的pac地址填上去

Android: 把系統的DNS伺服器地址設定為上面的IP。 
已ROOT, 想方便設定的人可以使用Set DNS 直接設定: SetDNS設定里打開override 3G/WiFi, 再回到主介面, 列表中點custom, 然後再輸入DNS的IP。
沒有ROOT的人請打開設定>WIFI>按住自己用的WiFi網絡>修改網絡>顯示進階選項>IP設定，由DHCP轉為靜態，然後再輸入DNS的IP。

----------

## 技術說明：

新的 unblock 伺服器簡單來說就是用了 #106 的privoxy 再串上 WIKI上的Nodejs代理
另外再運行了 dns 轉發伺服器配合記錄了需解鎖域名的資料庫

##### 一般域名
User-> US IP DNS -> 3rd party DNS -> get the resolved IP
User-> internet -> target server

##### 白名單域名/包含特殊URL時
User -> US IP DNS / PAC script -> get the Proxy IP
User-> US IP Proxy server -> China server -> internet -> target server

#### 速度和安全性可以這樣高->低比較:
1. 自己架設nodejs 或 自己有國內IP代理配合PAC 做特殊URL轉發
2. 單純privoxy特殊URL轉發向unblockyouku伺服器 或 使用unblockyouku伺服器的pac檔做特殊URL轉發(DNS不變)
3. 使用unblockyouku的DNS反向代理

(1)使用ISP DNS, 連接一般網站時最佳, 除非nodejs / PAC 連接的國內IP代理出問題, 不然不會影響unblock。 
缺點: 看 #80

(2)使用ISP DNS, 連接一般網站時最佳, 而一旦unblockyouku伺服器出問題時將不能連接特殊URL, 造成不能unblock。 缺點: 用電腦架設privoxy的話同 #80, 而用路由器架設會有點複雜, 只使用pac的話將不支持android等。

(3)使用unblockyouku的美國DNS轉發器, 連接一般網站時取不到距離自己近的IP, 可能影響瀏覽/下載速度, 而且一旦unblockyouku伺服器出問題而用戶不懂改回DNS設定, 將不能上網。 好處是簡單方便通用。

----

## **01/27/2014 重大注意事項 - 公共DNS服務**
由於最近受到多次 **"DNS放大攻擊"** 的投訴, DNS服務將實行較嚴格的查詢速率限制。
這有可能會顯著影響您直接設定DNS後網絡瀏覽之速度及可靠性。

如攻擊情況持續, 短期內DNS服務將有可能無預警地被伺服器服務商關閉。
**萬一DNS服務遭關閉, 您直接設定DNS的裝置將可能不能正常上網, 此時您需要把DNS設定還原。**

預期在DNS服務遭關閉後, 反向代理部分仍能繼續運作
你可以通過安裝以下hosts檔, 把里面的IP改為伺服器IP, 又或者使用它來設置路由器內建的DNS服務，
以代替公共DNS之功能。
https://github.com/karlcheong/unblock_youku_privoxy_rules/blob/master/basehosts

多謝這些天來各位之使用及意見!
karlc.

----

## 状态监控 
Feb 10, 2014 新添了 DNS 的状态监控

[![](https://share.pingdom.com/banners/bbaa09dc)](http://stats.pingdom.com/7w8lzo3be6k1/1113903)

详细的历史信息可以访问
http://stats.pingdom.com/7w8lzo3be6k1/1113903

**Comment by steve1108** [comment]
Hi @karlcheong 

Can u add this domain to ur dns Reverse Proxy Server : api.itv.letv.com .
I think it should be use Letv box and Letv TV of AUTH...
Thanks.

Steve

**Comment by ivyontheway** [comment]
网站：爱奇艺
呃......播放失败了
移动端上：
网络不给力，请稍后重试

平台：Win8+Mac OS+Ipad
ISP：香港网上行

dns和pac都有尝试

**Comment by karlcheong** [comment]
fixed

sent by Karl, from gmail.

2015-02-02 21:29 GMT+08:00 ivyontheway <notifications@github.com>:

**Comment by tywtyw2002** [comment]
建议把这个issue的内容总结一下写入wiki，然后从新起一个issue，260+的回复load起来很慢，维护性不佳

**Comment by gitawego** [comment]
同意。。。的确看起来很吃力。。。

**Comment by mkliu** [comment]
今天早上从android看搜狐还可以，晚上打开时候就不行了。从浏览器试图打开视频的时候说503 service unavailable. pingdom倒是没有看到down time

**Comment by kclonline** [comment]
請問各位iqiyi能觀看嗎?
Chrome和Android手機都不能看:'(
但其他平台很正常。

**Comment by li0001** [comment]
这两天在iPad上下载都不能下载。也没有说是在美国地区的原因就是下载不了。乐视app也无法下载，请问是不是都DNS有问题了

**Comment by zhuzhuor** [comment]
@li0001 最近我们服务器遭到 拒绝服务 (DoS) 攻击，见 #452
