### ISSUE TITLE
某些地區進入 iQiyi網站 動漫分類 的所有頁面都會 轉到404頁面

### ISSUE THREAD

**Issue by karlcheong** [zhuzhuor/Unblock-Youku#123]
遇到了個奇怪的問題
訪問奇藝動漫 www.iqiyi.com/dongman/ 這個以下
所有的URL都會跳出302-> www.iqiyi.com/error.html

國內代理可以看到
用Zenmate其他的國家地區IP代理連接時
英國,德國,瑞士可以看到
美國,香港 就會轉到404頁面

iQiyi IP封鎖升級了?? 只擋下動漫分類, 但郤不擋電影電視劇? 

不知有沒有人遇到相似情況

**Comment by zhuzhuor** [comment]
这个问题好像现在没有了
