### ISSUE TITLE
无法观看sina直播

### ISSUE THREAD

**Issue by sherlockhou** [zhuzhuor/Unblock-Youku#218]
已经下载最新2.6.11.0 但是还是无法看新浪直播
求救

**Comment by enerai** [comment]
我也出现的是“节目加载失败”请重试，这个应该怎么排查问题呢？

**Comment by zhuzhuor** [comment]
@enerai 我这里也是加载失败
回头有空了看看

**Comment by zhuzhuor** [comment]
刚刚给 sina 体育直播新加了个 URL，见 https://github.com/zhuzhuor/Unblock-Youku/commit/bf184eb34f69042285f62e5fa3f35c772566b587

另外，我发现播放很久之前的直播视频总会显示加载失败什么的
但是找一个比较近期的的视频直播访问就没有问题

比如今天正在直播的这个就没有问题 http://video.sina.com.cn/l/pl/sportstv/1698151.html
>  ![Uploading Screen Shot 2015-08-07 at 11.55.34 PM.png…]()
