### ISSUE TITLE
芒果 TV

### ISSUE THREAD

**Issue by whuhacker** [zhuzhuor/Unblock-Youku#348]
http://www.hunantv.com/app/m/

大部分可以直接看，不过限制了 TVB 的剧集

**Comment by zhuzhuor** [comment]
@HelloBugs 虽然有点晚，[最新的代码更新](https://github.com/zhuzhuor/Unblock-Youku/commit/946a534b295ff726a26ab1371fc66215973dca64)已经修复了一些 hunantv 视频不能播放的问题，请等待 Chrome 扩展程序的更新


上面的关于电视盒的 Hunantv App 的问题，看起来貌似是不能重现？
如果依旧有问题再来 reopen 这个 issue 吧
