### ISSUE TITLE
最近sohu视频好像新增加了新的验证机制？？？已经无法看了

### ISSUE THREAD

**Issue by hafa2012** [zhuzhuor/Unblock-Youku#356]
最近sohu视频好像新增加了新的验证机制？？？
我用聚合软件，比如兔子视频看sohu的源，进入播放就很慢，好像要反复重试多次，
后来，虽然勉强出现画面，可根本看不了，10秒钟左右就卡住不动了，切换清晰度没用，快进也没用，
而且用sohu的tv版本也出现一样的现象，
sohu肯定是加强了视频播放的验证机制，而这种验证机制对采用unblock方式的海外用户起到了影响，
现在sohu的内容已经基本都看不了啦，
@karlcheong 请来看看，，，因为sohu里独家的片子很多，，，要是不能看就可惜了。。。感谢

其实sohu以前很流畅的。。。。。
btw，我在澳洲,用到是安卓电视盒，修改dns的方法

**Comment by bearzk** [comment]
我打开这个地址
http://tv.sohu.com/20141101/n405674845.shtml

显示的是
亲爱的用户，该视频内容存在异常，无法提供观看服务了，向我们留言反馈

**Comment by zhuzhuor** [comment]
sohu 的这个问题还存在吗？
我试了试一些视频，都好像可以正常播放（不用 Chrome 扩展程序的话会显示海外不能播放）
唯一的问题是广告显示不出来，也没有文字提示倒计时什么的... 也就是视频播放前要干等好一会才行

**Comment by juehai** [comment]
Ipad 上用 sohu 的 app 看海贼王还是不行，我之前试着抓过 dns 的包，没找到要找的内容，谁给普及一下sohu 的验证方式？
