### ISSUE TITLE
虾米www.xiami.com跪了

### ISSUE THREAD

**Issue by WTIFS** [zhuzhuor/Unblock-Youku#381]
手机app正常，网页版今天突然不行了
chrome版本：38.0.2125.122 m

**Comment by caili-zhang** [comment]
用extension 的 switchy sharp加中国代理服务器的方法
以下的播放页面不能播放
http://www.xiami.com/play?ids=/song/playlist/id/2080049/object_name/default/object_id/0#open

不过个人的电台可以播放，图片都能加载就是不能播放
http://www.xiami.com/radio/play/id/2?spm=a1z1s.3522041.1110823061.2.FquVV0
虾米猜电台可以
http://www.xiami.com/radio/play/id/2
我用switchy sharp 的enable switch rule 如下
www.xiami.com/*

**Comment by WTIFS** [comment]
推荐用网易云，虽然部分歌曲也有版权限制，但至少不会像虾米一样进都不让进了_(:з」∠)_

**Comment by hantek** [comment]
报个到，加拿大已经全挂。另@JimJarvis，在这还能碰到你。。。
