### ISSUE TITLE
一直都用Ipad 的那个代理看优酷... 最近都开不了了.. 

### ISSUE THREAD

**Issue by dylanleeeee** [zhuzhuor/Unblock-Youku#386]
一直都用这个代理http://yo.uku.im/proxy.pac 看的...  求有没有别的方法用ipad 看优酷？

**Comment by annayan** [comment]
可以下个解锁软件Unblockcn，通过软件可以身在海外随时浏览大陆视频、音乐网站，不再受地域限制，重点是完全免费！
