### ISSUE TITLE
推荐 migrate 到百度云

### ISSUE THREAD

**Issue by whuhacker** [zhuzhuor/Unblock-Youku#388]
[百度云 BAE](http://developer.baidu.com/cloud/rt) 3.0 版使用了[类似 docker 的技术](http://developer.baidu.com/wiki/index.php?title=docs/cplat/bae)，以前禁封的函数全面开放。我试用了一段时间，感觉成本比 SAE 要低很多，特别是我们这种低计算高流量需求的应用场景。

资源独享，256MB 内存实例一天 0.4 元人民币，默认带宽为 5MB/s，不论流量大小，该部分不额外计费 

我部署了一个 urlproxy，[测试链接](http://tmp14170610549594246.duapp.com/proxy.php?url=http://1111.ip138.com/ic.asp)

不过据 @karlcheong 说北京的一些 IP 会导致解封失效，可以详细测测

**Comment by zhuzhuor** [comment]
现在已经彻底不用 SAE 了，感觉不是很稳定，从国外上传代码也经常出问题

转发模式的服务器可以尝试转到 BAE 上，但是估计要用自己的域名的话，备案是个麻烦事
现在的转发模式是 CloudFlare -> Heroku -> Aliyun

**Comment by tywtyw2002** [comment]
转发可以直接squid去解析嘛，还可以缓存。
如果之后流量大可以考虑前端nginx 后端 ATS的架构，然后做北美的cache轮询。这样对国内出口的压力会小很多的。

**Comment by whuhacker** [comment]
申请 BAE 的 port 服务，可以实现域名免备案。
只是不能使用 80 端口罢了， BAE 会随机分配一个 IP-端口 组合，自有域名直接指向 IP 即可。

**Comment by zhuzhuor** [comment]
@whuhacker 
这种 PaaS 的服务一般都没办法架设 squid 这样的 http proxy
因为 PaaS 的 request router 如果没有特殊设置的话，会把
```GET http:///aaa.com/bbb.html```
这样的 request 里面的 aaa.com 信息给弄丢了
不知道 BAE 也是不是这样
