### ISSUE TITLE
pac设置后仍无法播放呢

### ISSUE THREAD

**Issue by sangsangmadang** [zhuzhuor/Unblock-Youku#392]
你好，我用pad设置了Wi-Fi里的pac如图，测试显示true，但是用chrome浏览器打开优酷视频，网页有时候无视频资源，有时候有，点进去视频网页就不显示呢，网址栏里地址后面不停增加x&x&x&......，求解？优酷app有时仍显示限制，有时可以播放。
![image](https://cloud.githubusercontent.com/assets/10387893/5605401/88e1f6c2-93c6-11e4-8daf-e59eb56c45eb.jpg)
![image](https://cloud.githubusercontent.com/assets/10387893/5605400/88e10abe-93c6-11e4-8234-0c30204f30ae.jpg)
![image](https://cloud.githubusercontent.com/assets/10387893/5605403/88f237da-93c6-11e4-9ef1-791ca05c365b.jpg)
![image](https://cloud.githubusercontent.com/assets/10387893/5605402/88f1c962-93c6-11e4-8507-9dea6011c89f.jpg)
![image](https://cloud.githubusercontent.com/assets/10387893/5605404/88f2ef04-93c6-11e4-93f2-2f347ad964d8.jpg)

**Comment by karlcheong** [comment]
@sangsangmadang 
youku 網頁版的問題目測與我們的服務無關
app的問題 或許你可以給出視頻ID,URL或者名字 以作測試
有一已知問題是 youku禁止某些北京IP(包括我們使用的服務器)解析某些視頻ID
