### ISSUE TITLE
最近视频卡的无法看，求救！

### ISSUE THREAD

**Issue by rexzhiwei** [zhuzhuor/Unblock-Youku#393]
本人住在新加坡，一直以来都是用手机来观看大陆视频及动漫，我是用 http://yo.uku.im/proxy.pac 代理，使用爱奇艺pps ，爱奇艺 ，和PPTV聚力观看。大概一个星期前，在我使用这些app 观看视频时，突然发现视频下载的很慢，以前都会在350kb/s - 450kb/s 。 现在播放时，会有几十秒保持在这个速度，然后会突然间停留在 20kb/s - 35kb/s 之间。以前看超清根本不会有问题，现在连清晰都卡。 
我后来也试了http://pac.uku.im/pac.pac ， 但还是一样，请问有谁知道怎么解决这问题？

**Comment by tywtyw2002** [comment]
你自己家网的问题，与unblock代理无关。
