### ISSUE TITLE
优酷会员说共享 IP 过多

### ISSUE THREAD

**Issue by fishy** [zhuzhuor/Unblock-Youku#397]
优酷会员说该账号共享 IP 过多禁止观看，有没有解决方法？

**Comment by karlcheong** [comment]
以我所知沒有。因為我們的代理IP就只有那幾個。
youku所有影片都得靠它們來連接。

**Comment by zhuzhuor** [comment]
@karlcheong 这个有点悲剧呢，看起来像是代理服务器 IP 越多更容易被禁用
可以让用户手动改 host 固定个 ip 试试看？

**Comment by karlcheong** [comment]
原來是代理DNS LB 造成解析地址時代理出口IP不同。
是可以通過HOSTS固定用一個代理IP。 也許可以在擴展中固定它...

**Comment by whuhacker** [comment]
代理 IP 现在有多少啊？优酷判定也太严了吧

**Comment by zhuzhuor** [comment]
@whuhacker 国内只有三个，PAC 只有一个
