### ISSUE TITLE
iPad優酷客戶端好萊塢電影失效

### ISSUE THREAD

**Issue by k1n** [zhuzhuor/Unblock-Youku#400]
iPad優酷客戶端好萊塢電影失效，抓包發現DNS有新地址。
push.m.youku.com
statis.api.3g.youku.com
user.api.3g.youku.com
static.youku.com

**Comment by zhuzhuor** [comment]
static.youku.com 有没有精细一点 url
怕有很多不必要的 data 也通过代理服务器了

**Comment by mc16888** [comment]
add this to the unblock list will fix the problem, api.mobile.youku.com
But I think you can fine tune it to avoid unnecessary data go through the proxy server.

iPad app made at least 3 request to this web site when try to play Hollywood movie.

http://api.mobile.youku.com/layout/ios3_0/play/detail?ouid=xxxxxxxxxxxxx
http://api.mobile.youku.com/common/shows/relate?ouid=xxxxxxxxxxxxxxxx
http://api.mobile.youku.com/videos/XODE5ODE0OTM2/comments?ouid=xxxxxxxx

**Comment by mc16888** [comment]
Pls disregard my previous comment, adding api.mobile.youku.com did not fix the problem

**Comment by mc16888** [comment]
Just do some packet capture and found out the play link is like this 
http://i.play.api.3g.youku.com/common/v3/play?&local_vid=xxxxxxxxxxxx

Current unblock rule is using below link
http://i.play.api.3g.youku.com/common/hasadv/v3/play?*

I think add the first link to the unblock rule will solve the problem.
