### ISSUE TITLE
关于QQ音乐PC版的问题

### ISSUE THREAD

**Issue by tommyzhaozbh** [zhuzhuor/Unblock-Youku#403]
之前曾经有留言说QQ音乐PC版可以使用改hosts或者是用改unblock DNS方法就可以甩开限制，很长一段时间都是可以的。但今天再打开的时候发现不行了，而且奇怪的是，网页版倒是啥事都没有，就是客户端不行。莫非是客户端还加了一层检测？本人在香港

**Comment by tommyzhaozbh** [comment]
![qq](https://cloud.githubusercontent.com/assets/8757104/6092171/983fd718-af0c-11e4-9895-0e49259a69e4.png)
原来是有新地址，i.y.qq.com，后面就开始get ip limit了

**Comment by HHGBC** [comment]
请问这个具体怎么操作？？？

**Comment by tommyzhaozbh** [comment]
@HHGBC 什么怎么操作？

**Comment by HHGBC** [comment]
你现在在香港能正常使用qq音乐了么？

**Comment by tommyzhaozbh** [comment]
@HHGBC 目前已经向作者推送请求加新的检测地址了，但现在好像还没回复。要等到作者同意添加之后才行

**Comment by karlcheong** [comment]
@tommyzhaozbh @HHGBC  
the change is live on the dns server

**Comment by HHGBC** [comment]
那live之后要怎么设置？  在IE里设置代理 然后在QQ音乐选择IE代理吗？

**Comment by HHGBC** [comment]
OK 我的弄好了 谢谢你们 XD

**Comment by HHGBC** [comment]
我的现在可以听歌了 但是还是没有办法搜索歌曲 和看里面的音乐馆 乐库 请问这个有办法解决吗？

**Comment by tommyzhaozbh** [comment]
@HHGBC 我这里已经没有问题了，你那边怎么设置的？

**Comment by tommyzhaozbh** [comment]
@karlcheong Right. I've submitted pull request to your unblock_youku_privoxy_rules and pls check it :)

**Comment by karlcheong** [comment]
@tommyzhaozbh the repo wasn't updated since my desktop broke down months ago and it misses dozen of rules. Will update soon.

**Comment by HHGBC** [comment]
@tommyzhaozbh 我是在IE里面 LAN里面设置了automatic configuration： http://pac.uku.im/pac.pac  然后在QQ音乐软件里选择了IE代理
请问这样设置是对的吗？

**Comment by zhuzhuor** [comment]
Merge @tommyzhaozbh 的 pull request #404 的时候这个 issue 被 github 自动关闭了
如果有后续问题可以手动再打开 

@HHGBC IE 对 PAC 的处理貌似有点问题，参见 #164 
你需要使用 PAC 的话可以试试别的浏览器，例如 Firefox

@karlcheong 台式机出问题了吗，严重吗

**Comment by tommyzhaozbh** [comment]
@HHGBC 不要使用这种方法，因为IE不支持通配符。看这里：#164
我一般使用两种方法，一个是修改hosts，一个是修改DNS。前者方法看164，后者就在网络连接那里把DNS改为192.241.222.103。注意：如果你用改hosts的方法的话，记得要加两行
192.241.222.103  s.plcloud.music.qq.com
192.241.222.103  i.y.qq.com
前者对网页版，后者对PC客户端

**Comment by HHGBC** [comment]
@tommyzhaozbh 哈哈 现在好了 太感谢了

**Comment by HHGBC** [comment]
@tommyzhaozbh 请问这个是不是已经失效了？ 我今天用不能用了。。。 请问有新的服务器吗？？

**Comment by tommyzhaozbh** [comment]
@HHGBC 我刚刚看了一下，没有发现新的服务器。不过因为192.241.222.103这个服务器开始不是很稳定，刚才测试的时候发现返回503的。所以这里换一下服务器：104.236.189.178。把hosts里头的地址都换了应该可以了。
