### ISSUE TITLE
在一个同样有墙的国家，通过一个欧洲得vps，squid代理出去，想看国内视频，怎么破？

### ISSUE THREAD

**Issue by dragonone** [zhuzhuor/Unblock-Youku#405]

**Comment by zhuzhuor** [comment]
你可以看看 https://github.com/zhuzhuor/Unblock-Youku/issues/331

**Comment by tywtyw2002** [comment]
squid 后端接unblockyouku 的服务器，或者直接中国的服务器。

大体和这个类似https://github.com/tywtyw2002/unblockyouku_squid  这个集成了更多的功能。
上面的是比较新的配置。
这个是以前写的 https://github.com/zhuzhuor/Unblock-Youku/wiki/%E8%AE%A9Squid%E5%B8%A6%E6%9C%89Unblock-Youku%E5%8A%9F%E8%83%BD
综合一下看看，对会squid的基本很easy就能看懂。

**Comment by dragonone** [comment]
#331 的方法有点复杂，而且还需要由国内的服务器，这边连国内的服务器相当慢，不然也不会选择欧洲得服务器

**Comment by sequoiar** [comment]
@dragonone

if you want, send an email to iwebpp@gmail.com, we can share a browser for
you

2015-02-10 16:07 GMT+08:00 dragonone <notifications@github.com>:

**Comment by dragonone** [comment]
描述下现状：
1. 所在国家有墙，且链接国内的VPS异常慢，时延到秒级，带宽100kbps级
2. 链接欧洲得VPS很快，时延100ms级，带宽到2mkbps级，看youtube完全没问题
3.链接欧洲得vps后看国内视频会block
这么个情况各位大师有啥建议否

**Comment by karlcheong** [comment]
如果你的歐洲VPS連接國內很快
正如 @tywtyw2002 所說, 可以在VPS上部署代理伺服器
把urls列表里的地址轉發到國內代理／unblock youku代理
然後連接到VPS上看國內視頻
