### ISSUE TITLE
unblock [DNS] 伺服器回報用帖 2

### ISSUE THREAD

**Issue by karlcheong** [zhuzhuor/Unblock-Youku#406]
#### **回報問題時請詳細描述問題, 附上你的地區/ISP/使用的平台/網站, 不然將有可能遭忽略!**
-----
原issue #112 回復太多， 特開一新issue用以回報問題。
以下內容來自 #112, (技術說明請看原issue)

-----

# **注意，使用本服務代表您同意以下條款**

1. 相對於 Chrome 擴展程式，這種代理伺服器的模式會有安全隱患。如果代理伺服器被黑，則可能造成個人隱私洩漏或財產損失。

2. 因為技術上的原因，這種代理模式在功能，連接可用性及反應速度可能會受各種因素影響。

# **程式作者及伺服器提供者對任何可能的後果概不負責。**

#### 測試進行時有問題可以在這里回復

----

## DNS代理比一般PAC代理多了以下功能：

1. DNS+反向代理: 就是類似unblock-us那樣，利用DNS+反向代理解封國家限制，只是針對的是中國而不是美國, 用戶可以通過修改DNS設定連接到伺服器。 For reference: https://trafficserver.apache.org/docs/trunk/admin/reverse-proxy-http-redirects/ 。
2.  PAC代理，DNS開放非常規端口給位於透明代理/防火牆後的用戶, 以解決類似 #104 問題
3.  伺服器接入HE的IPv6隧道(記得某個帖中有人問IPv6的需求) 
4.  破解部分Apps 廣告,影片下載限制 (只限使用DNS並/或自行修改host,pac) (不保證能用)
5.  OpenDNS / Norton DNS 過濾各種不良網頁。

．．．請提出你的建議

### 目前支持的OS
支持PAC的各種瀏覽器, iOS Apps, Android Apps

       由於開通了反向代理服務, Android也可以通過這個服務unblock youku 了喔!
       暫時測試支持的有(以支持Apps為主)
       Apps: youku, tudou, iqiyi, letv, tencent video, sohu, baidu music, qq music, kuwo, kugou, duomi, ttpod.....
       Webpage: youku, tudou, iqiyi, letv, tencent video, sohu, baidu music

### 設定值：
PAC地址：http://dns.umbridges2014.com/proxy.pac
非常規端口(8000) PAC地址：http://dns.umbridges2014.com/altproxy.pac
DNS IPv4地址：192.241.222.103
DNS IPv6地址：2001:470:832e:1024:6969:5269::1
DNS端口： 53,5353 udp tcp 
轉發模式後台： http://berryphp.ap01.aws.af.cm/digito.php

桌面電腦, iOS: 請看 http://ub.uku.im/proxy 把上面的pac地址填上去

Android: 把系統的DNS伺服器地址設定為上面的IP。 
已ROOT, 想方便設定的人可以使用Set DNS 直接設定: SetDNS設定里打開override 3G/WiFi, 再回到主介面, 列表中點custom, 然後再輸入DNS的IP。
沒有ROOT的人請打開設定>WIFI>按住自己用的WiFi網絡>修改網絡>顯示進階選項>IP設定，由DHCP轉為靜態，然後再輸入DNS的IP。 （也可以選用#259）

----------

## **01/27/2014 重大注意事項 - 公共DNS服務**
由於最近受到多次 **"DNS放大攻擊"** 的投訴, DNS服務將實行較嚴格的查詢速率限制。
這有可能會顯著影響您直接設定DNS後網絡瀏覽之速度及可靠性。

如攻擊情況持續, 短期內DNS服務將有可能無預警地被伺服器服務商關閉。
**萬一DNS服務遭關閉, 您直接設定DNS的裝置將可能不能正常上網, 此時您需要把DNS設定還原。**

預期在DNS服務遭關閉後, 反向代理部分仍能繼續運作
你可以通過安裝以下hosts檔, 把里面的IP改為伺服器IP, 又或者使用它來設置路由器內建的DNS服務，
以代替公共DNS之功能。
https://github.com/karlcheong/unblock_youku_privoxy_rules/blob/master/basehosts

多謝這些天來各位之使用及意見!
karlc.

----

## 状态监控 
Feb 10, 2014 新添了 DNS 的状态监控

[![](https://share.pingdom.com/banners/bbaa09dc)](http://stats.pingdom.com/7w8lzo3be6k1/1113903)

详细的历史信息可以访问
http://stats.pingdom.com/7w8lzo3be6k1/1113903

**Comment by mkliu** [comment]
刚才不小心在另一个thread报了。今天早上从android看搜狐还可以，晚上打开时候就不行了。从浏览器试图打开视频的时候说503 service unavailable. pingdom倒是没有看到down time。在西雅图，comcast网络

**Comment by k1n** [comment]
地區：香港
ISP：香港寬頻
使用的平臺：MAC OS X，iOS，Android
網站：網頁優酷，網頁土豆，優酷Android APP，網易雲音樂Android APP，網易雲音樂iPhone APP。。。
問題：


Error 503 Service Unavailable

The page you requested is unavailable due to:

Service Unavailable

You can goto our Github project site for help.
Quick Info

PAC: http://dns.umbridges2014.com/proxy.pac

Alternative PAC (Port 8000): http://dns.umbridges2014.com/altproxy.pac

DNS IPv4 Address: 192.241.222.103

DNS IPv6 Address: 2001:470:1f04:c8b::2
Unblock Youku Server

**Comment by mkliu** [comment]
now it's back

**Comment by k1n** [comment]
http://v.youku.com/v_show/id_XMzY2NzQ1Mzcy.html
显示“版权原因无法观看”，抓包似乎有新的地址。

http://v.youku.com/QVideo/~ajax/getVideoPlayInfo?__rt=1&__ro=&id=91686343&sid=46823&type=vv&catid=96

**Comment by zhuzhuor** [comment]
@k1n
这个视频应该不只是海外不能看
用了国内的代理服务器代理还是不能看

**Comment by kclonline** [comment]
请问各位iqiyi能观看吗?
Chrome和Android手机都不能看:'(
但其他平台很正常。
http://www.iqiyi.com/v_19rrhfwcj0.html#vfrm=2-3-0-1

**Comment by k1n** [comment]
地区：香港
ISP：香港宽频
使用的平台：MAC OS X
网站：tv.sohu.com

MacBook-Air:~ k1n$ nslookup tv.sohu.com
;; connection timed out; no servers could be reached

**Comment by ysuolmai** [comment]
请问有什么方法可以抓到安卓的app用了什么验证url吗？目前dns或者自己架设privoxy都没有办法绕过优酷xl电视版 （安卓平板可以绕过！）。我想应该是有新的验证地址了

**Comment by houtianze** [comment]
我只想说，非常感谢。

**Comment by delphiste** [comment]
你好，我是ublock youku的用户。

我家里有几个国内带来的安卓盒子。我现在将192.241.222.103设为盒子的DNS，这样盒子也可以看优酷之类的视频了。谢谢你们的劳动。

有一个问题就是能不能麻烦您将小米盒子的ICNTV和天猫魔盒的华数播控平台的地址也加入proxy list，这样从国内带来的盒子就能全功能的用起来，不至于一打开盒子就是”您所在的地区无法播放该视频“。毕竟小孩子很喜欢的巧虎一类这些平台都有。

谢谢

**Comment by yanggis** [comment]
K大，192.241.222.103DNS现在还能用吗？怎么ping通了，在Android盒子上设置这个DNS，直接网都上不了啊。

**Comment by gaosong2101** [comment]
用了dns之后会出现网易云音乐app用户界面无法加载的情况，恢复默认dns以后恢复正常，望修复。
澳大利亚，Adam internet，Android（多个版本的网易云音乐），使用ipv4 dns

**Comment by yanggis** [comment]
@gaosong2101 这个DNS192.241.222.103早就不能用了。

**Comment by gaosong2101** [comment]
我一直在用啊，一直都可以用，只是有这个问题罢了。

**Comment by llq25** [comment]
ipad ios9 美国
使用的爱奇艺和哔哩哔哩客户端
截止前天为止都可进行视频缓存，今天全挂了。
麻烦技术人员辛苦了！

**Comment by gp020083** [comment]
![1](https://cloud.githubusercontent.com/assets/17728296/14495403/40506556-01ca-11e6-842a-6fe318df3c34.jpg)
这么设置不对吗?

**Comment by yanggis** [comment]
你这是没法判断对还是不对的，比如你浏览器有没有设置其他的代理，你有没有用其他的解锁软件，你的hosts文件有没有清空并重启电脑等等。但是可以保证如果你电脑上仅仅用了DNS一种解锁方法看乐视视频和爱奇艺应该是没问题的。如果你几种交叉着用，那就很难判断到底哪里出问题了。最简单的办法就是把你的手机上网DNS 改一下看看乐视视频能不能看就清楚了。如果可以就是你电脑的问题。
