### ISSUE TITLE
qq视频无法看了 

### ISSUE THREAD

**Issue by 9shi** [zhuzhuor/Unblock-Youku#407]
chrome unblock youku

**Comment by karlcheong** [comment]
沒發現問題
請給出詳情
比如 視頻名字／URL，你所在的地區和出問題的截屏

**Comment by 9shi** [comment]
http://film.qq.com/cover/0/02h84kc25zlho0k/p0015r953m9.html
抱歉，根据您当前的IP地址，该地区暂不提供播放。
如有问题请联系我们进行反馈

**Comment by karlcheong** [comment]
我這里沒有看到問題，請問QQ其他視頻有沒有問題（特別是一般非VIP的視頻）
還有請說明一下你所在地區和使用的網絡公司／ISP

**Comment by 9shi** [comment]
我知道了問題了,chromebook系統不知道為什麼強制使用了html5

**Comment by harrywy** [comment]
我也有同样的问题 就是QQ视频
http://v.qq.com/cover/b/bubnr6zzqq584j8/x0016menqle.html
youku可以的

**Comment by karlcheong** [comment]
我這里沒有看到問題 , 請說明一下你所在地區和使用的網絡公司／ISP

**Comment by 9shi** [comment]
@karlcheong @harrywy 網站不知道為什麼把原來的播放器flash改為html5,很可惜地目前沒有任何直接方法解決,我肯定完全不關網絡供應商問題,因為當我用同一網其他電腦是可以的,這是騰訊視訊的問題,有一個方法去解決,網站的視訊編號,強行修改為flash

**Comment by harrywy** [comment]
@9shi 有意思我刚才是在linux下不能看 不过在win8下又可以...

**Comment by 9shi** [comment]
@harrywy 也許明天試一試做一個更換html5播放器的t

**Comment by 9shi** [comment]
暂时变通方法点击视频左下方的分享按钮，复制flash地址在新标签页打开会出来flash播放器。
http://tieba.baidu.com/p/3590169405

**Comment by karlcheong** [comment]
有方法手動切換html5的么。。又或者你們能提供chrome 的developer tool 的記錄呢？。
說不是有新的地址需要加入

**Comment by tommyzhaozbh** [comment]
@karlcheong @9shi 看了一下，有新的检测
![qq](https://cloud.githubusercontent.com/assets/8757104/6326693/42bf7a66-bb8f-11e4-9ffd-1fc88e7995da.png)
![qq 2](https://cloud.githubusercontent.com/assets/8757104/6326694/42e44eae-bb8f-11e4-97c9-3045c3e10637.png)
![qq 3](https://cloud.githubusercontent.com/assets/8757104/6326695/430b5ea4-bb8f-11e4-958f-82361fd77d58.png)
![qq 4](https://cloud.githubusercontent.com/assets/8757104/6326696/433223fe-bb8f-11e4-8899-b0812e3d87af.png)
暂时不清楚究竟是哪一条发挥了作用

**Comment by zhuzhuor** [comment]
这个问题应该是好了？我刚才试了下 @harrywy 提供的链接，就算登录 QQ 帐号，也还是可以播放
