### ISSUE TITLE
qq 体育直播不行了

### ISSUE THREAD

**Issue by shifrank** [zhuzhuor/Unblock-Youku#408]
昨天还看了一场扣篮大赛 今天不知道怎么了
网址http://sports.qq.com/kbsweb/basket.htm?matchId=1466882&competitionId=100000
chrome版本40.0.2214.111 m
Unblock Youku 2.7.6.3
![default](https://cloud.githubusercontent.com/assets/11022105/6205723/53120e12-b53e-11e4-862c-421c78f52703.PNG)

**Comment by karlcheong** [comment]
已修復 請等待擴展更新

**Comment by shifrank** [comment]
谢谢
