### ISSUE TITLE
看樂視(LETV)直播很慢....經常緩衝

### ISSUE THREAD

**Issue by gx3541** [zhuzhuor/Unblock-Youku#412]
看樂視(LETV)直播很慢....經常緩衝(特別是體育賽事)

但是觀看其他非直播的樂視(LETV)節目會很順暢,很快.....

是那裡出了問題呢?

謝謝!

**Comment by karlcheong** [comment]
因為直播的unblock機制不同限制了cdn只能使用國內的，而點播的不會。
可試試把代碼中插入xforwardfor header的IP值改成中国移动/联通/其他的ISP再試試
gx3541 <notifications@github.com>於 2015年3月1日 週日，上午3:13寫道：

**Comment by gx3541** [comment]
謝謝回覆
請問是不是修改這裡 (chrome/header.js)
-------------------------
function header_modifier(details) {
    console.log('modify headers of ' + details.url);

    details.requestHeaders.push({
        name: 'X-Forwarded-For',
        value: unblock_youku.ip_addr
    }
--------------------------
將 unblock_youku.ip_addr 更改成 中国移动/联通的ISP
THX!

**Comment by zhuzhuor** [comment]
@gx3541 对，你可以改个这里的 value 成别的 ip 地址看看

**Comment by lwk523** [comment]
@karlcheong   .你好，我可以联络你吗？ May I have you email address?

Thank you
