### ISSUE TITLE
可以通过这样的原理去跳过BBC的访问限制吗？

### ISSUE THREAD

**Issue by Sofronio** [zhuzhuor/Unblock-Youku#413]
把shared\tools.js里的ip地址模拟成英国ip
但是水平有限，fiddle看了半天也没看出来是哪个网址在判断ip。。。

求指教

**Comment by cnbeining** [comment]
公开一下私下的结果：

判断地址：```http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/{programme_ID}```

可行方式：

- 挂UK代理
- UK转发

请注意```*.bbc.co.uk```在中国大陆的极大撞墙可能。

I am putting it here for now...

**Comment by 9shi** [comment]
@cnbeining  You are here .......................

**Comment by cnbeining** [comment]
@9shi Yeah, everywhere includes your nightmare :-D

Kindly reach me via cnbeining[at]gmail.com , since I do not want to pollute this issue...

**Comment by 9shi** [comment]
@cnbeining ok (you are being watched ,your friend has a secret , A man or lady that watch you everyday wwwwwwwwww)

**Comment by cnbeining** [comment]
那啥 我还记得你的之前的通信。。。所以请戳过来吧。。。

为啥之前每次我戳回去的时候都没回复了呢。。。

**Comment by Sofronio** [comment]
Thanks for sharing the open.bbc.co.uk address.
It really helps a lot.
I use a PAC HTTP proxy, and add the open.bbc.co.uk to the rule, and then it works fine!

**Comment by Sofronio** [comment]
use a proxy on the following address could bypass the limitation of region.
for BBC
open.live.bbc.co.uk
for ITV
mercury.itv.com
