### ISSUE TITLE
Iphone 的xiami apps 不行了...

### ISSUE THREAD

**Issue by chioran** [zhuzhuor/Unblock-Youku#414]
192.241.222.103好像不行了。。。怎麼辦??

**Comment by dicklaw** [comment]
192.241.222.103 has no response today

![screenshot 2015-03-15 21 33 39](https://cloud.githubusercontent.com/assets/504476/6656181/138c9b9e-cb5b-11e4-906d-c185c31b59f5.png)

![img_20150315_165818092_hdr 1](https://cloud.githubusercontent.com/assets/504476/6656186/2d20fb5e-cb5b-11e4-9661-f7084c1e86f4.jpg)
