### ISSUE TITLE
192.241.222.103 has no response today

### ISSUE THREAD

**Issue by dicklaw** [zhuzhuor/Unblock-Youku#415]
192.241.222.103 has no response today

![screenshot 2015-03-15 21 33 39](https://cloud.githubusercontent.com/assets/504476/6656181/138c9b9e-cb5b-11e4-906d-c185c31b59f5.png)

![img_20150315_165818092_hdr 1](https://cloud.githubusercontent.com/assets/504476/6656186/2d20fb5e-cb5b-11e4-9661-f7084c1e86f4.jpg)

**Comment by dicklaw** [comment]
It works again now.
Thank for your contribution !

**Comment by tommy880113** [comment]
192.241.222.103最近好像對土豆, 優酷的ANDROID APP 用不了..能檢查看看嗎?
