### ISSUE TITLE
不可以下载

### ISSUE THREAD

**Issue by litan1106** [zhuzhuor/Unblock-Youku#417]
2 把basicsetting里的設定文件解壓, 放到 /etc/privoxy

https://www.dropbox.com/s/7ae1o14e0357id2/basicsetting.7z  (不可以下载, 404)

password: karlcheong

**Comment by zhuzhuor** [comment]
@karlcheong

**Comment by karlcheong** [comment]
Now on https://github.com/karlcheong/unblock_youku_privoxy_rules
