### ISSUE TITLE
Youku: episode selection pane of copyrighted TV shows are blocked (videos still play)

### ISSUE THREAD

**Issue by zmwangx** [zhuzhuor/Unblock-Youku#420]
I'm using the Unblock Youku Chrome extension (version  2.7.6.4) in normal mode, and something seems to have happened in the past 24 hours that broke Youku support for at least a certain class of TV shows. For instance, the following show (among others) is blocked due to copyright restrictions even when Unblock Youku is enabled: http://v.youku.com/v_show/id_XODI1MzY1NDc2.html

Relevant HTML:
```HTML
<div class="items">	
  <div title="版权限制，暂无法播放" class="item" name="tvlist" flag="1" seq="20" id="item_XODI1MzY1NDc2">
    <span class="sn_num_limited">01</span>
  </div>
  <!-- other episodes... -->
</div>
```
Screenshot:
![blocked due to copyright restrictions](https://i.imgur.com/cwsyPlF.png)

Meanwhile, other services that I know of seem unaffected. For example, the same show on Tudou (which actually uses the same backend as Youku) can be successfully unblocked: http://www.tudou.com/albumplay/aCSw2edHPfo.html

By the way, I'm in the U.S., in case geographic location matters.

**Comment by zmwangx** [comment]
By the way, redirect mode doesn't work either.

**Comment by zhuzhuor** [comment]
It is OK for me for the same Youku video.
Could you check if you have other extensions installed specifically for Youku?

> ![screen shot 2015-03-31 at 4 20 09 pm](https://cloud.githubusercontent.com/assets/928905/6928413/daa8ee68-d7c1-11e4-824c-9666d5c5b379.png)

**Comment by zmwangx** [comment]
@zhuzhuor Oh my bad, I can confirm that the video actually plays fine. (I use click to play, so I didn't even load the Flash plugin after seeing the copyright messages. Sorry for the floppiness in testing.) I should go ahead and change the title of this issue.

Anyway, the episode selection pane on the right is now blocked (also shown in your screenshot). Is it possible to bring that pane back to action?

Just for the record, I've disabled all other extensions before testing.

**Comment by zhuzhuor** [comment]
Thanks. I also noticed that. Tudou sometimes has the same issue.
I will look into it soon.

**Comment by tommyzhaozbh** [comment]
@zhuzhuor It seems that this issue is very difficult to settle. I've checked the source of the Chinese characters "版权限制，暂无法播放" are actually embedded in the main page. 
![qq](https://cloud.githubusercontent.com/assets/8757104/7154939/4ba31004-e38d-11e4-9ae3-e8c2a40ed8c2.png)

So it seems that the main page has checked the IP address and then shows the message.

**Comment by zmwangx** [comment]
@tommyzhaozbh Well, what you noticed has always been in my first post, in case you haven't seen it.

**Comment by zhuzhuor** [comment]
I just verified that: if the main HTML page "http://v.youku.com/v_show/*" goes through the proxy, the selection panel will have proper content. Otherwise, there will be an empty list.
It seems for now the only solution is letting all such pages with selection panels go through proxies in China. But it would be a heavy load for our proxy servers and slow down users' general connections to Youku. I will think about it.

**Comment by zmwangx** [comment]
Thanks for the investigation. In that case I'd say let's just keep it as is, since many (if not most) shows are not blocked, and in those cases passing all http://v.youku.com/v_show/ pages through proxy would be a waste on both ends. Google is usually pretty good at locating a specific episode anyway.

**Comment by zhuzhuor** [comment]
@zmwangx OK. Thanks for understanding.
I will reopen this issue if anything changes.

**Comment by tommyzhaozbh** [comment]
@zhuzhuor Problem solved. Everything becomes fine now. Maybe Youku has unblocked the panel.
![qq](https://cloud.githubusercontent.com/assets/8757104/8613469/0c473d5e-2712-11e5-87ac-e20355c80989.png)

**Comment by zmwangx** [comment]
@tommyzhaozbh 

> Problem solved. Everything becomes fine now. Maybe Youku has unblocked the panel.

Not for me though. The panel doesn't even show up.

![screen shot 2015-07-09 at 11 47 15 pm](https://cloud.githubusercontent.com/assets/4149852/8613527/f5c0f4b2-2694-11e5-84fa-d615376ee720.png)

Again, it probably depends on geolocation (or luck).
