### ISSUE TITLE
爱奇艺客户端发现新检测地址

### ISSUE THREAD

**Issue by tommyzhaozbh** [zhuzhuor/Unblock-Youku#421]
该死的爱奇艺在今天添加了一条新的检测地址了，明明早上还能看的晚上居然看不到了……一气之下用wireshark检查，果然有新发现。
![qq](https://cloud.githubusercontent.com/assets/8757104/6985271/32332578-da64-11e4-803f-a370ffb63910.png)
这条地址是直接发给unblock-dns的，但因为名单没有这地址，所以返回的结果是这样的：
![qq](https://cloud.githubusercontent.com/assets/8757104/6985291/6a2f6a5e-da64-11e4-996a-7ff6c359a71d.png)
然后我用国内的代理试了一下这条链接，结果……
![qq](https://cloud.githubusercontent.com/assets/8757104/6985308/8ac81036-da64-11e4-9a8a-c9b043122257.png)
连视频真实地址都出来了（我可以盗链了么？）那应该是新地址惹的祸了。

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 不知道修改还没生效还是我添加的规则有问题，现在还是不行……

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 现在好了吗，chrome web store 更新之后需要一两天才能把更新 push 给用户

**Comment by zhuzhuor** [comment]
你可以留个有问题的视频地址，我也看看

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 这东西不是网页版的，是爱奇艺PC客户端的。测试连接是这个：http://cache.video.qiyi.com/vp/356401400/9781d6b77f7651e552f81e3fd728005d/?src=606b62b5b934470485fb8053e6705521
现在爱奇艺PC客户端走的连接就是这种连接格式的，但是即便在hosts设置了，在IE测试的时候还是这个样子。也就是说unblock dns没法识别我的连接

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 是说主要是 DNS 的问题吗
DNS 是 @karlcheong 全权在弄，不知道他什么时候有空

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 是的，因为这东西是客户端不经过浏览器。另外问一个：unblock DNS的列表是不是和chrome插件的列表不同步更新的？

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 对， DNS 的列表应该没有同步更新，应该是因为和浏览器用的有点不同吧

**Comment by karlcheong** [comment]
@tommyzhaozbh 
已更新。
列表的確是手工更新的。因為urls.js格式和privoxy／squid的格式不同。

**Comment by zhuzhuor** [comment]
@karlcheong 感谢更新！
