### ISSUE TITLE
不能观看新浪 NBA 直播

### ISSUE THREAD

**Issue by enerai** [zhuzhuor/Unblock-Youku#424]
开 unblock youku 虽然不提示“不在服务地区”，但是依旧不能播放，但是连接国内代理翻回国之后就可以看了，猜测是 unblock youku 的问题。

测试链接：http://video.sina.com.cn/l/pl/sportstv/1695289.html

**Comment by enerai** [comment]
诶，为什么问题关闭了？

**Comment by zhuzhuor** [comment]
我试了下现在可以看
估计是这直播地址总是改变的缘故，之前也有类似的问题 https://github.com/zhuzhuor/Unblock-Youku/issues/218
如果之后再遇到问题欢迎再来 open 这个 issue

![screenshot 2015-05-10 12 52 30](https://cloud.githubusercontent.com/assets/928905/7555263/770a3206-f713-11e4-8d1f-53bec7346bf2.png)
