### ISSUE TITLE
FireTV 用Unblock-Youku 的DNS看国内视频，会突然卡住

### ISSUE THREAD

**Issue by Hao-Luo** [zhuzhuor/Unblock-Youku#425]
刚开始播放的时候缓冲很快，基本上是秒放。
但是没过几分钟速度就会变成0KB/S，看起来像是断开了链接。
使用的是Unblock-Youku的DNS服务。
麻烦看一看。

服务商是英国的 BT Infinity. 带宽是35Mb/s

**Comment by tommy880113** [comment]
192.241.222.103最近好像對土豆, 優酷的ANDROID APP 用不了..能檢查看看嗎?
