### ISSUE TITLE
B站正版全部都看不了

### ISSUE THREAD

**Issue by TungNg** [zhuzhuor/Unblock-Youku#426]
在iPad 上
現時所有［BiliBili正版］都完全看不了
顯示「獲取視頻信息失敗」

希望unblock youku 能夠支援一下
感謝了

**Comment by yan12125** [comment]
在電腦上 (Chrome or Firefox etc.) 能用嗎？

**Comment by zhuzhuor** [comment]
感谢。这两天也有别人跟我提起
估计就是 https://github.com/zhuzhuor/Unblock-Youku/issues/427 的问题

这个 issue 就 close 了，后续的问题请在 #427 里回复
