### ISSUE TITLE
proxy.uku.im:8888 Can't resolve host names anymore

### ISSUE THREAD

**Issue by yan12125** [zhuzhuor/Unblock-Youku#427]
Here are some curl invocations. First I use full host names:
```
$ curl -v -x proxy.uku.im:8888 "http://hot.vrs.sohu.com/vrs_flash.action?vid=2319043"
*   Trying 211.155.86.25...
* Connected to proxy.uku.im (211.155.86.25) port 8888 (#0)
> GET http://hot.vrs.sohu.com/vrs_flash.action?vid=2319043 HTTP/1.1
> Host: hot.vrs.sohu.com
> User-Agent: curl/7.42.1
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 503 Service Unavailable
< Server: nginx
< Date: Sat, 09 May 2015 03:59:15 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 383
< ETag: "5271cad2-17f"
< X-Cache: MISS from localhost
< X-Cache-Lookup: MISS from localhost:8888
* HTTP/1.0 connection set to keep alive!
< Connection: keep-alive
< 
<html>
<head>
<title>The page is temporarily unavailable</title>
<style>
body { font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body bgcolor="white" text="black">
<table width="100%" height="100%">
<tr>
<td align="center" valign="middle">
The page you are looking for is temporarily unavailable.<br/>
Please try again later.
</td>
</tr>
</table>
</body>
</html>
```
And then I use IP addresses:
```
$ curl -v -x proxy.uku.im:8888 "http://220.181.118.55/vrs_flash.action?vid=2319043"
*   Trying 211.155.86.25...
* Connected to proxy.uku.im (211.155.86.25) port 8888 (#0)
> GET http://220.181.118.55/vrs_flash.action?vid=2319043 HTTP/1.1
> Host: 220.181.118.55
> User-Agent: curl/7.42.1
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: nginx
< Date: Sat, 09 May 2015 03:55:43 GMT
< Content-Type: text/html; charset=UTF-8
< dispatcher: 123.125.123.82
< Pragma: No-cache
< Cache-Control: no-cache
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< X-Cache: MISS from localhost
< X-Cache-Lookup: MISS from localhost:8888
< Connection: close
< 
{"preview":2,"holiday":0,"p2pflag":1200,"isp2p":0,"isai":0,"id":2319043,"prot":2,"ct":4019,"nt":10,"allot":"220.181.61.240","reserveIp":"123.125.123.82","vt":1,"tn":5,"sp":1024,"status":1,"wexp":0,"play":1,"pL":30,"url":"http://tv.sohu.com/20150408/n410951635.shtml","uS":-1,"fms":0,"fee":0,"caid":2,"caname":"电视剧","pid":7039435,"isdl":0,"ispv":0,"isNewsLogo":0,"preload":0,"systype":0,"age":"","year":2014,"areaId":10,"mainActorId":"22347;13642;7931","act":"","tv_application_time":"2015-04-08 12:00:00","catcode":"101112;101115;101117;101124","pvpic":{"big":"http://photocdn.sohu.com/Transcod/BackUp_Transcod/images/svc/20150408/1608959_1001766359_pad_H_133148_15009/1608959_1001766359_pad_H_133148_15009_big_160_90_15.jpg","small":"http://photocdn.sohu.com/Transcod/BackUp_Transcod/images/svc/20150408/1608959_1001766359_pad_H_133148_15009/1608959_1001766359_pad_H_133148_15009_small_60_33_15.jpg"},"tvid":1608959,"islpc":1,"syst":1431143743774,"voteId":"229;228","voteRegion":1,"isdrm":0,"dm":0,"eye":0,"data":{"tvName":"疑犯追踪第4季第19集","subName":"","ch":"tv","fps":25,"ipLimit":1,"width":852,"clipsURL":["http://data.vod.itc.cn/tv/Sample1/BackUp_Sample1/svc/20150408/1608959_2319043_tv_H_133146_17283/1608959_2319043_tv_H_133146_17283_001.mp4","http://data.vod.itc.cn/tv/Sample1/BackUp_Sample1/svc/20150408/1608959_2319043_tv_H_133146_17283/1608959_2319043_tv_H_133146_17283_002.mp4","http://data.vod.itc.cn/tv/Sample1/BackUp_Sample1/svc/20150408/1608959_2319043_tv_H_133146_17283/1608959_2319043_tv_H_133146_17283_003.mp4","http://data.vod.itc.cn/tv/Sample1/BackUp_Sample1/svc/20150408/1608959_2319043_tv_H_133146_17283/1608959_2319043_tv_H_133146_17283_004.mp4","http://data.vod.itc.cn/tv/Sample1/BackUp_Sample1/svc/20150408/1608959_2319043_tv_H_133146_17283/1608959_2319043_tv_H_133146_17283_005.mp4","http://data.vod.itc.cn/tv/Sample1/BackUp_Sample1/svc/20150408/1608959_2319043_tv_H_133146_17283/1608959_2319043_tv_H_133146_17283_006.mp4","http://data.vod.itc.cn/tv/Sample1/BackUp_Sample1/svc/20150408/1608959_2319043_tv_H_133146_17283/1608959_2319043_tv_H_133146_17283_007.mp4","http://data.vod.itc.cn/tv/Sample1/BackUp_Sample1/svc/20150408/1608959_2319043_tv_H_133146_17283/1608959_2319043_tv_H_133146_17283_008.mp4","http://data.vod.itc.cn/tv/Sample1/BackUp_Sample1/svc/20150408/1608959_2319043_tv_H_133146_17283/1608959_2319043_tv_H_133146_17283_009.mp4"],"version":1,"clipsBytes":[18203434,18241351,18267950,18278905,18344025,18213163,18338031,18246204,12645079],"num":19,"coverImg":"http://photocdn.sohu.com/20150408/vrs1608959.jpg","height":480,"totalDuration":2608.901,"totalBytes":158778142,"clipsDuration":[300.002,300.002,300.002,300.0,300.002,300.002,300.002,300.002,208.887],"relativeId":2319043,"norVid":2319044,"highVid":2319043,"superVid":2319118,"oriVid":0,"h2644kVid":0,"h265norVid":0,"h265highVid":0,"h265superVid":0,"h265oriVid":0,"h2654mVid":0,"h2654kVid":0,"totalBlocks":9,"ck":["-gl756LeVe-ihE-nl0NXkY0eV3uem7kd","i8WT4HZeVs3wY8bhKP6K785dlv6VRCQ3","3P4CBWOBUCZOTYEs8uvsq-m-J6HQmlb-","7L_eHgYYDs2yBJmG8pMPmrp4ZQdv_AFn","NSVqABqQ_CONVKX97HqFgkkl1Gm-_8MU","J9l0JjiKJuE2PJNlgl0sndVEWLACCOw2","jDpyu24hZUCDXfjFBiXbgC1zQDd1E9MA","XOFbn2RRM5JEflDlBA1Whya-HsWBfuuR","Tx4lfhbmWGyWAdNw78yrNS2-33OXlUh-"],"hc":["F5NWJY3SC5R3SZVJEDYQNSYKEMOCOAZ3","URD6SWVMGZ7GLEJMDSQ5NBVJONTQ54EN","QWIVDMWFW5FA7BYVKLDZB6U4NXPVPH32","AJIWCXGMKQLQNYDUBAVZQR7WVFMMR3BD","C273GFTX5QZZK6P7WBLGF6X34ZAH43KH","2WQ6XX4YSEDH6OPXXDEC2UCCCTQGR63E","JRJ73VYFI5KQEJQXJ47CHW3D2WY5QPF5","IPHLG5A7CWA5E7WAONAS6P7EV3DYLGSQ","CI6734CGXJ3QQ5YSX44B7LWEX5GQNNDY"],"su":["/11/108/dtMFM6LeRAebvoDhyy1B5D.mp4","/84/71/tP6HnHfpQeaIYv0Q2Of4qB.mp4","/36/247/PfQBeWcwS7qQoI06k9cigG.mp4","/146/150/n5mhcyCKQ79FxFbI9KMx8Z.mp4","/51/176/LAVWXwA1Ttmyo7D9Zn3V2E.mp4","/215/212/VD22X8vMJNxILYaHbAf8dB.mp4","/17/23/tcHzxEdqT8nQhhpoFYw17E.mp4","/185/100/9aex8JubEpJnkPynbzGXTD.mp4","/44/151/BrU96U8yEbtiDCh4q3qEZH.mp4"],"sT":0,"eT":0,"eP":null,"adpo":null,"xlClipsDuration":[0],"xlClipsBytes":[0],"xlClipsUrl":null},"oriType":-1,"fnor":0,"keyword":"疑犯追踪第4季;疑犯追踪第4季第19集;疑犯追�* Closing connection 0
��第4季全集;疑犯追踪第4季电视剧;悬疑剧;科幻剧;动作剧;惊悚剧;","company":"50056","crid":338,"plcatid":2,"cmscat":"251366993;261789159;261789193;349107470;403098869;410951635","uvr":null,"hcap":1,"scap":null}
```
And here's a wireshark capture for using unblock youku in Firefox:
![unblock_youku](https://cloud.githubusercontent.com/assets/1937689/7549315/96b7c070-f662-11e4-91ec-87518f4030fa.png)

Such a problem is causing performance downgrade for clients that fallback to IP addresses and break those who use only hostnames.

Is it intended to prevent proxy.uku.im:8888 from third-party accesses? If so, please respond a 403 rather than 503.

**Comment by zhuzhuor** [comment]
The server of proxy.uku.im is fully maintained by @karlcheong. I am not sure what's the root cause for this problem. Please wait for @karlcheong's reply/fix.

**Comment by cowbert** [comment]
The browser plugin still works though. I have not looked at the plugin code at all, but I thought it just set the correct proxy string based on the hostname regex? If so, doesn't the proxy still resolve the hostname in this way?

**Comment by zhuzhuor** [comment]
@cowbert The Chrome extension is using different proxy servers (HTTPS-based) than proxy.uku.im.
The servers except proxy.uku.im and DNS are maintained by me (although all the servers are paid by me). proxy.uku and DNS are maintained by @karlcheong. It seems he is really busy recently (the same for me). Hope he can find some time to check this problem soon.

**Comment by TungNg** [comment]
感謝@zhuzhuor 和@karlcheong 的努力
但其實B站的問題在大約一個月前已經出現了
不過不要緊了，有時間再處理吧

**Comment by yan12125** [comment]
> The Chrome extension is using different proxy servers (HTTPS-based) than proxy.uku.im.

@zhuzhuor Is the server listed in [proxy.js](https://github.com/zhuzhuor/Unblock-Youku/blob/master/chrome/proxy.js#L49) the alternative server?

**Comment by zhuzhuor** [comment]
@yan12125 Yes, that's the proxy server for the Chrome extension.
It only supports HTTPS proxy due to the issue https://github.com/zhuzhuor/Unblock-Youku/issues/320

**Comment by zhuzhuor** [comment]
The server behind proxy.uku.im seems to have reached its bandwidth limit, which is 5Mb/s for input/output.

![screen shot 2015-05-19 at 5 46 04 pm](https://cloud.githubusercontent.com/assets/928905/7714751/5371bf42-fe4f-11e4-8089-6320ce41a109.png)

**Comment by whuhacker** [comment]
This issue caused Unblock Youku Firefox extension not working properly either.

@zhuzhuor Shall we setup a new proxy in China?

**Comment by yan12125** [comment]
@whuhacker Is it possible to use https://proxy.mainland.io:993/ in firefox? Or better, let users choose which proxy to use?

**Comment by zhuzhuor** [comment]
@whuhacker I have been very busy lately (catching up a deadline). Do you want to set a Squid proxy by your own? The config files for the Squid server have been shared with you in another repo. I will take a look when I have more free time soon.

BTW, the servers behind proxy.mainland.io seem under DDoS attacks now. See https://github.com/zhuzhuor/Unblock-Youku/issues/429#issuecomment-103919690

**Comment by zhuzhuor** [comment]
The bandwidth usage of the proxy.uku.im server increases to more than 10 Mb/s now...
This's definitely not normal. It was about 5Mb/s even 10 days ago. (Even 5Mb/s is too large to my view).
I am not sure what's happening. But it definitely has some problems/issues.

> ![screen shot 2015-05-28 at 1 12 02 pm](https://cloud.githubusercontent.com/assets/928905/7866107/3be0f738-053b-11e5-86c2-6a900ade463b.png)

**Comment by yan12125** [comment]
I have some guess. The majority of users of proxy.uku.im:8888 are firefox users. From my previous wireshark screenshot, 1 request becomes 3 requests. As a result, traffic becomes 3 times than the old days.

**Comment by zhuzhuor** [comment]
@whuhacker It seems Firefox also supports the HTTPS proxy now. See https://bugzilla.mozilla.org/show_bug.cgi?id=378637
Maybe you can have a try.

**Comment by whuhacker** [comment]
@zhuzhuor Sure. Thanks

**Comment by cowbert** [comment]
FWIW, I have been using the Firefox version of Unblock-Youku and have not
had any issues with it for the past month.

**Comment by yan12125** [comment]
This problem does not exist anymore. I've tried the two ```curl``` commands as well as captured the packets from the Firefox plugin, all of which work properly. I'm closing the issue now.

And lots of gratitude towards all efforts on maintaining such a great project!
