### ISSUE TITLE
乐视直播无法看

### ISSUE THREAD

**Issue by hwhenry2015** [zhuzhuor/Unblock-Youku#428]
乐视网直播会显示因版权方要求该视频只能在乐视网内播放。但点播就没问题。
其他网的直播也没问题

**Comment by zhuzhuor** [comment]
能提供个有问题的视频链接吗？

**Comment by hwhenry2015** [comment]
http://live.letv.com/sports/play/index.shtml?type=zb&id=1020150519162318

**Comment by zhuzhuor** [comment]
这个问题在最近的代码更新里修复了 https://github.com/zhuzhuor/Unblock-Youku/commit/c29ff203d098cbda69c04fd908b251a42940e0c7
请等待 Chrome Web Store 上面的更新

如果过一段时间更新了还是不行的话，请再来 reopen 这个 github issue
