### ISSUE TITLE
新加坡设dns法对虾米android手机版5.0.5无效

### ISSUE THREAD

**Issue by oglops** [zhuzhuor/Unblock-Youku#433]
http://ipservice.163.com/isFromMainland 是true
我电脑上打开www.xiami.com 或者是 手机apps都显示你不在中国大陆，手机是lollipop 5.0.1 note 3, 虾米版本5.0.5
这说明也许虾米决定把这个ip地址封了么....

我是在路由器里（asus rt-n66,tomato firmware）设的，也试过改手机hosts文件，2个月前可以，后来就一直不行直到今天

网上看评论说某些海外时差党现在依然可以用，不知为何新加坡不行.... 特此汇报

**Comment by xkk** [comment]
chrome插件下虾米网页打不开 Xiami is currently not available in your country.
网页中插入的虾米播放器也有同样问题
chrome：43.0.2357.124
unblock youku：2.7.6.9
新加坡

**Comment by zhuzhuor** [comment]
才注意到这个是 xiami 的问题
参见 https://github.com/zhuzhuor/Unblock-Youku/issues/381
虾米的付费 VIP 的一个功能就是海外可以正常使用，所以我们不打算在我们的扩展程序里支持 xiami
