### ISSUE TITLE
土豆不能观看

### ISSUE THREAD

**Issue by yzh89** [zhuzhuor/Unblock-Youku#434]
估计和土豆网页更新有关

**Comment by RiceeeChang** [comment]
星期四看不到銀魂好痛苦

**Comment by lmz110014** [comment]
快来人解决啊~~~~土豆不能看！我要看火影啊！！！

**Comment by zhuzhuor** [comment]
http://www.tudou.com/albumplay/92J2xqpSxWY.html 

类似这个吗？我这里也的确是不能正常播放

**Comment by zhuzhuor** [comment]
刚刚修复了  https://github.com/zhuzhuor/Unblock-Youku/commit/d272ab421585706425397e230d81103a85427d19#diff-41aa484bd1cb407067baa0bc2761f236R4
等等 Chrome Web Store 的更新吧，估计短的话一两个小时就能收到更新

如果回头还有问题欢迎再来 reopen 这个 issue
