### ISSUE TITLE
爱奇艺视频连接失败

### ISSUE THREAD

**Issue by tommyzhaozbh** [zhuzhuor/Unblock-Youku#440]
最近在爱奇艺上看视频总是碰上这个
![default](https://cloud.githubusercontent.com/assets/8757104/7976325/271f2f7e-0aac-11e5-824b-c57d9742b755.PNG)
因为爱奇艺在海外貌似也有部署CDN，所以我们这些大陆以外的地方全部都会指向到这个地址
![default](https://cloud.githubusercontent.com/assets/8757104/7976443/a68ca0ce-0aad-11e5-9413-e8ba612c0ed5.PNG)
因为是跨域名访问，因此需要调动crossdomain.xml。但问题是我看了一下F12,发现里头的crossdomain.xml总是跳403 Forbidden。
![default](https://cloud.githubusercontent.com/assets/8757104/7976416/386e601e-0aad-11e5-840e-9de4b45c49d7.PNG)
直接访问crossdomain就变这个
![default](https://cloud.githubusercontent.com/assets/8757104/7976485/3f72da7e-0aae-11e5-920a-37aa88fcfb4f.PNG)
然后我试着开国内代理再访问，结果……
![default](https://cloud.githubusercontent.com/assets/8757104/7976496/7419bf7c-0aae-11e5-885e-cb7b5ac187f7.PNG)
也就是说，现在爱奇艺换了一种方式拦截海外用户：把海外用户指向海外CDN（netcnoversea.inter.iqiyi.com），但在海外的CDN却禁止flash播放器访问crossdomain.xml，这就直接导致flash播放器没法访问位于海外CDN的视频文件。至于让crossdomain.xml走代理能不能解决这个问题这就不清楚了，得试一下。
(PS：最近爱奇艺封杀海外用户很厉害，光是客户端都已经改了好几次检测地址。我真的怀疑是不是有人盯上了这里……）

**Comment by zhuzhuor** [comment]
估计他们在更新后台架构吧

我这里试了下，就算用上国内的代理 http://netcncoversea.inter.iqiyi.com/crossdomain.xml 也是 access denied，感觉比较奇怪

有啥链接没，我也具体看看

**Comment by whuhacker** [comment]
我在国内，访问 也是 access denied

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 这就奇怪了，我刚刚回家也试了一下，发现即便用了代理也不行，都是403. 不知道究竟怎么回事。至于视频链接……应该来说所有视频都没法看，都是这个。（PS：我在香港）

@whuhacker 那你有没有试过视频能不能正常播放？我这里是压根没法正常跳转到真正的视频地址。

**Comment by zhuzhuor** [comment]
我随便试了几个，的确都是没法看，比如这个
http://www.iqiyi.com/v_19rroizqjg.html
用不用扩展程序都是显示 浏览器兼容性或网络问题
整个浏览器全过代理服务器就能正常播放

**Comment by zhuzhuor** [comment]
添加了一个新的 iqiyi 的 url 到列表里，貌似是解决了问题
我试了一两个视频，如果能挺到广告播完的话貌似视频就能正常播放... 但是很多时间都是卡在广告上，广告 load 不出来，倒计时就不动，iqiyi 这是作死啊

你们这两天也多试试，如果解决问题了就好
如果没能完全解决问题，再来 reopen 这个 issue

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 问题没有解决，广告会卡死。然后如果用广告拦截软件的话依旧还是没法看。

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 多谢这详细的信息，我试试看

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 我试了这个视频 http://www.iqiyi.com/v_19rroizqjg.html 昨天貌似还可以的，今天还是不能正常观看
你说的 data.video.iqiyi.com 的链接在我这个视频里没有啊，见下面的截图，你能给我个你遇到看到这个 link 的视频网页吗

> ![screen shot 2015-06-05 at 11 35 54 am](https://cloud.githubusercontent.com/assets/928905/8009526/6baad10e-0b77-11e5-98e0-2c3370d59ad8.png)

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 抱歉打错了，是qiyi.com，见我上面的截图。就拿你发的那个视频链接，我这边是这样的。
![qq](https://cloud.githubusercontent.com/assets/8757104/8010201/cbd5368c-0be0-11e5-8816-da4f6fc8c1fe.png)

**Comment by zhuzhuor** [comment]
多谢，最后就照你说的把那个 URL 加进去就好了
而且我也照你说的仔细看了下，视频文件都在那个海外的 CDN 上，但是 crossdomain.xml 文件却下载不下来。个人猜想是 iqiyi 的内部 bug 吧，不然应该没必要只把视频文件放在海外专用的  CDN 上

另外，我还尝试了下 redirect 那个 crossdomain.xml 的连接去我们自己的文件 http://git.io/vIYnD
可以成功 redirect，但是视频还是播放不了，猜测是 Flash 处理 crossdomain 文件的机制的原因

以后如果能有简单的办法让通过 squid 的文件内容更改，或者直接用 chrome 的 api 来修改 http response 就好了

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 那现在就坐等更新好了。另外把crossdomain redirect是没用的，因为它必须是目标服务器上面的crossdomain才有用。
不过这次还是辛苦你了。

**Comment by zhuzhuor** [comment]
貌似最新版上传到 Chrome Web Store 被标记成人工审核了，估计得过两天才能 push 给用户
PS，我也不太清楚到底啥时候需要人工审核啥时候不需要，可能是有算法来 flag 一些可疑的 updates，然后再用人工来审核

> ![screen shot 2015-06-07 at 11 44 46 am](https://cloud.githubusercontent.com/assets/928905/8024688/a8bfb52a-0d0a-11e5-8fb0-1bd0cd7beb22.png)

**Comment by nancyli8000** [comment]
今天可以看了，貌似修好了

**Comment by tommyzhaozbh** [comment]
@nancyli8000 确实是修好了，刚试了一下确实可以了。
@zhuzhuor 虽然现在iqiyi是修复了海外CDN的问题，但我发现海外CDN的速度远远不及国内的（起码在家里是这样）。如果服务器压力太大的话就把这条规则取消掉吧。

**Comment by Bozh** [comment]
我在香港，好像又不行了？我看到我这里unblock youku的版本是2.7.6.9
![screen shot 2015-06-15 at 8 29 02 pm](https://cloud.githubusercontent.com/assets/7104410/8159850/3cef305c-139d-11e5-8db1-06df751df790.png)

**Comment by zhuzhuor** [comment]
@Bozh 我这里刚试了几个都还可以，你再试试？是所有的 iqiyi 视频都不行吗

**Comment by Bozh** [comment]
@zhuzhuor 还是不行，所有的iqiyi都是播放失败。我把所有Chrome的插件都禁了，只留unblock youku也不行。Chrome Version 43.0.2357.124 (64-bit), Mac OS X 10.9.5

**Comment by zhuzhuor** [comment]
@Bozh 你试试下载源码，删掉这一行 `'http://data.video.qiyi.com/*/videos/*' `
然后在 chrome://extensions 页面手动安装修改过的源码，看看能不能解决你的问题

**Comment by tommyzhaozbh** [comment]
@Bozh 我刚刚测试了一下是没有问题的，因为现在连接的CDN是在山东，距离比较远，刷新一次就好。

**Comment by Bozh** [comment]
@zhuzhuor 抱歉迟了回复。请问是把shared文件夹下urls.js中的`http://data.video.qiyi.com/*/videos/*`删掉吗？我试了一下好像还是不行？如果大家都可以的话，难道是我其他地方的设置有问题。。想不到是哪里。。
