### ISSUE TITLE
Unblock youku doesn't work anymore! need Help!

### ISSUE THREAD

**Issue by JenXC** [zhuzhuor/Unblock-Youku#442]

**Comment by JenXC** [comment]
![image](https://cloud.githubusercontent.com/assets/12928799/8198117/1b1e3274-1470-11e5-897c-4d212d8dc3c8.png)

**Comment by zhuzhuor** [comment]
I just tested the same video, and it worked on my end. 
Do you want to check it again later (especially when disabling all the other extensions)?


> ![screen shot 2015-06-16 at 10 55 30 pm](https://cloud.githubusercontent.com/assets/928905/8198873/ea39370c-147a-11e5-9908-1825bbb77126.png)

**Comment by JenXC** [comment]
nothing has changed I disabled all the other extensions already!

**Comment by JenXC** [comment]
![image](https://cloud.githubusercontent.com/assets/12928799/8221318/f59dbbbc-152a-11e5-9f22-0fa7d28058a4.png)
the dame thing

**Comment by zhuzhuor** [comment]
Your location/region/country?

**Comment by JenXC** [comment]
canada

**Comment by zhuzhuor** [comment]
I am at Canada as well, but didn't experience your problem. We have to wait to see if other users/developers have the similar problem

**Comment by JenXC** [comment]
alright, but this situation started a week and a half ago though.

**Comment by JenXC** [comment]
I tried to delete it an re-download  and I even tried to re-download chrome too, but nothing happend

**Comment by tommyzhaozbh** [comment]
It works well on my site. Nothing unusual happened

**Comment by JenXC** [comment]
nah, it still doesn't work.

**Comment by tommyzhaozbh** [comment]
How about trying unblock DNS?

**Comment by JenXC** [comment]
how do u do that

**Comment by tommyzhaozbh** [comment]
That is easy. Just change the network connection settings. There is one setting about DNS. Just set it as 192.241.222.103.

**Comment by gorsonh** [comment]
我表示和楼主有同样问题。。。美国纽约，一时可以连接，大部分时间出现楼主的问题。

**Comment by zhuzhuor** [comment]
@gorsonh 最近代理服务器受到 DoS 攻击，所以你不一定是遇到了和楼主一样的问题，见 https://github.com/zhuzhuor/Unblock-Youku/issues/452

**Comment by zhuzhuor** [comment]
@JenXC Does this issue still exist? Did @tommyzhaozbh's method solve your problem?

**Comment by JenXC** [comment]
I just tried using unblock youku now and it works just fine. it did not try  @tommyzhaozbh's method cus I am not good computers, anyways the problem is seemed to be solved.

**Comment by JenXC** [comment]
thx anyway

**Comment by zhuzhuor** [comment]
@JenXC Thank you very much for the feedback!
