### ISSUE TITLE
Doesn't seems to work on youku.com anymore, tried all 3 modes.

### ISSUE THREAD

**Issue by fatsheep75** [zhuzhuor/Unblock-Youku#444]
Doesn't seems to work on youku.com anymore, tried all 3 modes.

**Comment by zhuzhuor** [comment]
Could you first try the potential solutions given in the page http://uku.im/faq
If the problem still persists, please provide more info about your problem, such as the specific links to the youku videos you were experiencing the problem, for us to investigate it.
