### ISSUE TITLE
在 sohu 不能正常工作（与其他扩展冲突）

### ISSUE THREAD

**Issue by enerai** [zhuzhuor/Unblock-Youku#448]
目前同时启用了 unblock youku 和 ADfree.Player.Online (https://chrome.google.com/webstore/detail/adfreeplayeronline/gnpjhfjhgfkohgdklomfbjmnchpenngp) 这两个扩展（安装顺序是先安装 unblock youku，再安装 ADfree.Player.Online）

安装之后，两个扩展同时在 youku，tudou，和 iqiyi 下面工作正常，既没有“地区限制”，也没有广告。但是在 sohu 上面则提示“地区限制”，不知道是 unblock-youku 还是 ADfree.Player.Online 那边的问题呢？

测试链接：http://tv.sohu.com/20150513/n412947109.shtml

谢谢！
(记得早点加上支付宝的途径哈哈)

**Comment by tommyzhaozbh** [comment]
ADfree Player这些去广告工具因为其工作原理的原因，会劫持了浏览器的代理权限，因为你是先安装unblock youku再安装ADfree，根据chrome的代理控制原则，ADfree会获得浏览器的代理权限。打开"设置-代理"，你会发现那里的代理是由ADfree来控制的，unblock youku这时候会失效的。
如果你觉得视频网站的片头广告很烦人的话，这里推荐你用两种广告过滤软件：一个是Adsafe，一个是广告拜拜。前者是通过在系统层面接管浏览器主程序的代理去完成过滤（不会影响unblock youku运作），同时也可以过滤软件内置广告（例如QQ音乐）。而后者目前只能过滤视频广告，但体积轻巧，我自己就在用这个。但无论你使用哪一款，他们都会破坏现有缓存而导致页面排版异常，所以使用前要先清理缓存。

**Comment by enerai** [comment]
感谢详细的回答^_^

但在这种扩展共存的我情况当中，在youku或者tudou的页面上unblock youku是可以生效的，不知道在这是怎么回事呢？按照道理来说，unblock youkj应该完全失效才对。

我现在用的是Mac，装不了那两个软件（哭了）

**Comment by tommyzhaozbh** [comment]
我刚看了一下，这插件有点奇怪的是他不完全获得代理权限的。这插件是需要通过本地代理来拦截广告并且让播放器顺利跳转到视频正片，但又不需要获得浏览器代理权限。换句话说，这两个软件其实可以共存。我试了一下，unblock youku其实是可以正常工作的，猜测可能是因为Adfree的规则和unblock Youku的规则发生冲突而导致抢代理。但可以肯定的一点就是，这两个插件有某种程度的不兼容，毕竟他们都需要用到代理。

**Comment by enerai** [comment]
也不知道修改起来麻烦不麻烦。。看来有空我得自己学学 Chrome 插件开发！哈哈

**Comment by zhuzhuor** [comment]
@enerai 如果都用到代理的权限，那应该会有冲突
对于有的网站是可以两个扩展程序都正常工作的，我的猜测是过滤广告在这几个网站上并没有依赖代理服务器吧

另外，之前有人提过兼容去广告扩展程序的 issue，我觉得我们没有必要去主动兼容这些扩展程序，你可以参考当时的讨论 https://github.com/zhuzhuor/Unblock-Youku/issues/234

**Comment by enerai** [comment]
@zhuzhuor 你自己当时在回帖当中明明写的是“我们本身就没有对 v.youku.com/crossdomain.xml 设置代理”所以是unblock youku没有设置代理。

哈哈顺便说一句，你这个wontfix标签页也真是搞笑。兼容的事情我是站在程序完美的角度上提的建议，对一个程序来说当然对其他影响越少越完美，而你站在“用户说想兼容去广告，我觉得这样不道德，完全没这个必要”的角度，去广告的问题其实大家讨论过很多遍了，如果你真的反对去广告，哈哈你去不兼容abp岂不是效果更好？广告的错不在他是广告，而在他是让人生厌的广告，每次播放60秒弱智广告给你看实在也是醉了。还有法律问题，访问网页之前没有accept一个用户协议，所以并没关系。去广告这个事情其实可以促进视频网站提升自己的态度，让他们知道用强塞骚扰性强的广告来盈利是会让用户反感的。顺便说一句，你觉得去广告不道德，OK，但道德这个事情只能拿来律己，律人就不明智了。

兼容的事情啊，我也就是提一下而已，你也不必要激动，淡定淡定。说了这么多，你觉得有用你就想一下，你觉得没用你就别看了，眼不见心不烦。

**Comment by zhuzhuor** [comment]
@enerai 不要激动...
我并没说过除广告不道德，你理解错了。我自己也装着 ublock，而且我个人也支持用户有选择观看下载到他们设备上的内容的权利。我只是想说我们不想去主动选择和兼容这些扩展程序
另外我个人也挺反感国内的超长时间广告。像 youtube 上面的广告模式就挺好的，希望国内厂商都能学习学习

首先我是想让我们自己的扩展程序生存地更加长远，这样也能有效地服务用户。之前也有人建议把过滤广告的功能直接集成到我们的扩展程序里，但是那样估计过不了多久就会被各大网站封锁吧
其次是这些反广告的扩展程序挺多的，特别是国内的这些反视频广告的程序良莠不齐（我知道之前有些扩展程序收集用户隐私的）。我们没有能力兼容所有的，也不好 endorse 其中的个别几个

如果你能自己修改源码也欢迎你改了代码自己来用，或者建议那个反广告的扩展程序来兼容我们的设定

**Comment by enerai** [comment]
哈哈 好的 我明白你的意思

**Comment by tommyzhaozbh** [comment]
你也别激动嘛，人家的意思是这插件在工作原理上比较难让步，毕竟他没有办法交出代理权限。而且市面上类似的插件很多，如果每个去广告插件都要去兼容的话这不实际，也不可能。而且ADP这类插件不需要用代理，只是监视浏览器访问的地址并对目标地址进行拦截，所以可以兼容。人家并没有说去广告是不道德的~~
其实如果要去广告，又要用unblock youku这类代理插件的话最好还是安装第三方软件为好。可惜你的是苹果系统，没办法。其实还有一个办法，就是用unblock DNS。把DNS地址改成192.241.222.103也能达到unblock的效果。

**Comment by zhuzhuor** [comment]
@enerai 
另外我看了下，#234 里的这句 “我们本身就没有对 v.youku.com/crossdomain.xml 设置代理” 其实是我开始理解错了 highpowerxh 的意思，我以为他说我们给 v.youku.com/crossdomain.xml 的设置造成的问题，是我当时的理解错误

也继续欢迎你给我们项目提出各种建议和意见
