### ISSUE TITLE
腾讯失效了

### ISSUE THREAD

**Issue by zkteh** [zhuzhuor/Unblock-Youku#449]
测试链接
http://v.qq.com/live/p/topic/1588/index.html

**Comment by zhuzhuor** [comment]
我这里是这样的，可以播，但是只是个宣传片
你是在直播的时候发现不能看的吗 

>  ![screen shot 2015-07-17 at 10 46 53 am](https://cloud.githubusercontent.com/assets/928905/8749675/30890e7c-2c71-11e5-9389-0a4df8b9e979.png)

**Comment by zkteh** [comment]
是的。

**Comment by zkteh** [comment]
其他视频是这样的。

![untitled](https://cloud.githubusercontent.com/assets/9402322/8750316/535c61d4-2cd9-11e5-8771-bfb6afa4fe0a.png)

**Comment by zhuzhuor** [comment]
我这里试了几个视频，都没有问题
你试试换成普通模式(Normal Mode) 试试看？
另外你有装别的扩展程序吗，可以发个 chrome://extensions 页面的截图给我们看看 

> ![screen shot 2015-07-17 at 11 20 36 am](https://cloud.githubusercontent.com/assets/928905/8750537/faa4032a-2c75-11e5-8381-ffa10c8454af.png)
> ![screen shot 2015-07-17 at 11 19 38 am](https://cloud.githubusercontent.com/assets/928905/8750538/faa77c8a-2c75-11e5-9796-159fc5add92c.png)

**Comment by zkteh** [comment]
啊！换成普通模式(Normal Mode)  就 解决了，谢谢！

**Comment by zhuzhuor** [comment]
解决了就好，感谢反馈

**Comment by zkteh** [comment]
@zhuzhuor  

直播不支持
![youku](https://cloud.githubusercontent.com/assets/9402322/9276199/13dee3f8-42d5-11e5-8f7e-80efe17a86d1.png)
