### ISSUE TITLE
192.241.222.103的DNS無效

### ISSUE THREAD

**Issue by hkhs10811** [zhuzhuor/Unblock-Youku#450]
最近使用192.241.222.103的dns，發現原本可以解除地域限制觀看的app突然都不能看了，是dns掛掉了？還是因為最近長城firewall又更新了？

**Comment by JackalZheng** [comment]
同問，我這邊是有時頁面無法開啓，偶爾開起來了，卻還是沒有解除限定的狀態。
18號就時好時壞，今天7/19就幾乎不能使用了。

**Comment by CaptainCan** [comment]
现在好像又可以用了

**Comment by hkhs10811** [comment]
@CaptainCan 真的耶
