### ISSUE TITLE
这什么东西,抄袭的么?

### ISSUE THREAD

**Issue by tommyzhaozbh** [zhuzhuor/Unblock-Youku#451]
今天在chrome store上搜unblock youku居然找到高仿的冒牌货，连名字都一样……
https://chrome.google.com/webstore/detail/unblock-youku/ciaifhgmoaecaojjneobbhhgdkgehojn?hl=zh-TW
![default](https://cloud.githubusercontent.com/assets/8757104/8795071/15047eb8-2fbc-11e5-8f3a-30b52eae3a45.PNG)

**Comment by zhuzhuor** [comment]
估计是有人故意提交的吧，那个来源网址指向的网站也是 NSFW...
Chrome Web Store 应该是不能交同名的扩展程序，可以点旁边的那个“检举”链接举报它。选“其它”，填上类似下面这样的理由
> `It's using the same name as the popular extension https://chrome.google.com/webstore/detail/unblock-youku/pdnfnkhpgegpcingjbfihlkjeighnddk/details`


 ![screen shot 2015-07-21 at 10 44 03 am](https://cloud.githubusercontent.com/assets/928905/8803631/dd71788c-2f95-11e5-9fb3-a8cfdef689ca.png)

**Comment by zhuzhuor** [comment]
好像 Chrome Web Store 已经移除这个扩展程序了
谢谢反馈！
