### ISSUE TITLE
服务器又遭 DoS 攻击

### ISSUE THREAD

**Issue by zhuzhuor** [zhuzhuor/Unblock-Youku#452]
扩展程序用的代理服务器和 DNS 用的服务器都遭 DoS 了，我们就等等吧

> ![screen shot 2015-07-27 at 11 29 27 pm](https://cloud.githubusercontent.com/assets/928905/8922901/920fd736-34b7-11e5-9903-f63fd0c0bdb6.png)
> ![screen shot 2015-07-27 at 11 29 09 pm](https://cloud.githubusercontent.com/assets/928905/8922904/9e8d380a-34b7-11e5-9f41-4ec5bf23a6a3.png)

感觉某个/某些人的人生、精力、金钱就浪费在这无意义的事情上了
有这时间金钱和精力干点啥不好

**Comment by whuhacker** [comment]
有利益冲突。Email 详聊

**Comment by tommyzhaozbh** [comment]
受此影响所有代理服务全部中断……又没得看视频了

**Comment by csyangning** [comment]
原来如此。。。希望快点回复。。。

**Comment by zhuzhuor** [comment]
这没完没了了，一会来一下

弄了个 public status page，可以来这里看服务器的状态
http://stats.pingdom.com/7w8lzo3be6k1

**Comment by tommyzhaozbh** [comment]
好消息：阿里云服务器已经恢复运作，工作正常

**Comment by alexking99** [comment]
難怪在android上修改的hosts用不了  什麼時候能恢復正常?

**Comment by chipang** [comment]
其实我们有没有办法可以架设这类Host  和DNS服务器，然后官方主服务器用不了还有第三方可以使用  谢谢~

**Comment by tommyzhaozbh** [comment]
同意楼上的，如果我们自己也有自己的服务器的话一方面可以减轻官方服务器的负担，另一方面也可以确保在主服务器被炸的时候还有其他的服务器可用。只是我们不是个个都是专家，没教程不会弄。现在服务器不时都被攻击，这样下去不是办法……

**Comment by zhuzhuor** [comment]
感觉给普通模式也能自定义代理服务器的功能有点刻不容缓了

在 aliyun 的代理服务器还挺麻烦的，为了避免 #320 的问题，全都弄成了 HTTPS
要么让用户自己弄 HTTPS 证书，或者用别的美团云等的服务器

**Comment by zhuzhuor** [comment]
给上面的 public status page 弄了个我们自己的域名，方便记忆 http://status.uku.im/

**Comment by alexking99** [comment]
求後備dns

**Comment by zhuzhuor** [comment]
@alexking99 DNS 服务器一直都是 @karlcheong 在弄，他好像最近有很长一段时间的都没有公开回复关于 DNS 的问题了。我自己也没有弄过那个 DNS，所以可能我们需要找新的志愿者来维护和开发 DNS 了

**Comment by tywtyw2002** [comment]
最近出什么问题了？

一直再忙。。。。。gtalk说

**Comment by zhuzhuor** [comment]
@karlcheong 多谢关照！

**Comment by fiveinches** [comment]
我想请问ipad和iphone突然不能看视频 是这个原因么

**Comment by zhuzhuor** [comment]
@fiveinches 你是 iphone 和 ipad 都用了 PAC 吗，如果的话就是这个问题

**Comment by zhuzhuor** [comment]
我稍微做了点操作，看看会不会有所改善，如果有人觉得之后情况变好了点可以留言

**Comment by alexking99** [comment]
@zhuzhuor 沒效果

**Comment by zhuzhuor** [comment]
@alexking99 只是对扩展程序的代理服务器弄了点措施，而且估计过一会才生效
DNS 不是我在维护，我没有管理权限，没有办法

**Comment by alexking99** [comment]
@zhuzhuor 不好意思 還以為是DNS  擴展有效果

**Comment by zhuzhuor** [comment]
@alexking99 DNS 这个估计不太好弄，最好的办法就是弄一套软件+教程让用户架设自己的 DNS 服务器

**Comment by fiveinches** [comment]
@zhuzhuor 是的 都用的pac 我还以为是我自己网络出了问题. 大概何时会解决呢. 辛苦了

**Comment by zhuzhuor** [comment]
@fiveinches 暂时只能等攻击告一段落了，PAC 的服务器一直是 @karlcheong 管理的，最近他好像没怎么活动了，我也不知道该怎么弄才好
我已经发邮件给 @karlcheong 问了问，如果他忙的话让别人来管理这服务器，看他也能来写个 DNS 的架设教程之类的不

**Comment by zhuzhuor** [comment]
@fiveinches 给 PAC 文件用的代理服务器做了个镜像服务器，看看情况

**Comment by fiveinches** [comment]
@zhuzhuor 刚试过 可以使用 辛苦了

**Comment by zhuzhuor** [comment]
@fiveinches 貌似镜像服务器也没能撑多久

**Comment by fiveinches** [comment]
@zhuzhuor 嗯 是的 刚试了一下 又变成false了

**Comment by hotmalex** [comment]
辛苦了

**Comment by aar0u** [comment]
今天网易云音乐突然所有歌(之前只有部分独立歌手的歌)全部提示“由于版权保护，您所在的地区暂时无法使用。" , 也是这个原因吗

**Comment by yihuigu** [comment]
@aar0u 应该是的，用DNS完全连不上网易云音乐，直连反倒没问题。

**Comment by alexking99** [comment]
@zhuzhuor 有沒有什麼新消息?

**Comment by zhuzhuor** [comment]
@alexking99 短时间内没办法吧，只能等什么时候攻击停下来了
如果我们没有比攻击者更多的网络资源，没什么好的解决办法。关于具体的 DDoS 攻击的介绍可以看 https://en.wikipedia.org/wiki/Denial-of-service_attack

关于 DNS 服务器的管理，我已经问了 @karlcheong，让 @whuhacker 维护看看
回头看 @karlcheong 或 @whuhacker 有没有空写个自己架设 DNS 的教程

**Comment by xiaoke11** [comment]
原来是这样 怪不得安卓的DNS app都挂了 ezunlock和ub翻墙都是在用这个dns咩还是他们也被DDoS给弄挂掉了？

**Comment by xiaoke11** [comment]
谁吃饱了撑着一直DDoS..

**Comment by w09351500** [comment]
一直不太明白，為什麼 Firefox 的 Unblock Youku 失效、Chrome 的卻能正常運行...

莫非又是 Google 黑科技了？

**Comment by whuhacker** [comment]
@w09351500 Firefox 版使用了不同的服务器，目前状态是被攻击下线

**Comment by w09351500** [comment]
@whuhacker 那麼有辦法連線至 Chrome 的 Unblock Youku 服務器嗎？

**Comment by jackielam1997** [comment]
能用cloudflare嗎

**Comment by thomastian1993** [comment]
多久才能解决呢，现在chrome的插件也不管用了。。。

**Comment by w09351500** [comment]
@thomastian1993 Chrome 的插件沒有問題，目前正常運行中

**Comment by nwxz215** [comment]
chrome的unblock youku好像也无法使用了，无法看国内视频网站。

**Comment by w09351500** [comment]
Youku 網站的確無法連線了，但是其他的貌似都沒有問題，先換個網站吧
2015年8月2日 下午12:53於 "nwxz215" <notifications@github.com>寫道：

**Comment by nwxz215** [comment]
可是我的上土豆还有湖南卫视的芒果tv都无法看视频。。

**Comment by nwxz215** [comment]
不好意思，我试了一下，又可以了，可能是我自己这边的问题，麻烦了。

**Comment by zhuzhuor** [comment]
@nwxz215 @w09351500 Chrome 扩展程序用的代理服务器也是时好时坏，我明天看看有啥临时的解决办法吧

**Comment by zhuzhuor** [comment]
@thomastian1993 见我在楼上给 alexking99 的回复 https://github.com/zhuzhuor/Unblock-Youku/issues/452#issuecomment-126722287

**Comment by nwxz215** [comment]
辛苦辛苦

**Comment by zhuzhuor** [comment]
@jackielam1997 见 #453 里我和 @tommyzhaozbh 的讨论

**Comment by zhxdl** [comment]
location美国刚刚测试了chrome国内几大视频网站（优酷，爱奇艺，土豆）还是无法看的状况。

**Comment by zhuzhuor** [comment]
@zhxdl 你可以在 http://status.uku.im/ 查看服务器最新的状态和历史

@xiaoke11 你说的是这两个 app 吗（为了避免变相给其做广告，就不贴 link 了）
那估计他们就是在用我们提供的免费服务吧
我们这代理服务器和 DNS 服务器都没办法做 access control，也挺头疼的

>  ![screen shot 2015-08-02 at 11 41 41 am](https://cloud.githubusercontent.com/assets/928905/9026992/897248c6-3911-11e5-88b9-4a1952233502.png)
> ![screen shot 2015-08-02 at 11 41 35 am](https://cloud.githubusercontent.com/assets/928905/9026993/89728732-3911-11e5-98cf-9ae0d6aeaf14.png)

**Comment by xiaoke11** [comment]
@zhuzhuor 是啊。。

**Comment by gorsonh** [comment]
最新更新， 北美3:30， 所有主流视频网站，正常连接了。

**Comment by w09351500** [comment]
PAC 仍舊無法正常運行

**Comment by xiaoke11** [comment]
不行 pac还是跪着

**Comment by zhuzhuor** [comment]
这攻击很有规律，都是北京时间早上8点开始，然后北京时间的晚上12点结束
估计就是针对香港、澳门、台湾的产品或者用户吧

@w09351500 @xiaoke11 PAC 和 DNS 都是用的美团云的服务器，我已经交给 @whuhacker 来管理了，等等他维护一下另外联系下美团云吧

**Comment by fireattack** [comment]
@aar0u 不是的，云音乐之前就没有封禁国外ip（不用unblockyouku也能听）从31号开始才封禁的。

当然以后如果unblockyouku能加入对云音乐的支持那是最好

**Comment by aar0u** [comment]
@fireattack 感谢解惑。求推荐其他好的音乐平台。
@zhuzhuor 请问unblock-youku可以加入网易云音乐的支持吗

**Comment by flinhong** [comment]
貌似搜狐视频win store客户端现在不用代理也可以看~~

**Comment by w09351500** [comment]
http://status.uku.im/

Unblock DNS (by @karlcheong) 顯示運行狀態，其他的還沒上線

**Comment by adamchan1023** [comment]
我是澳洲的User, Unblock youku到現在還是用不了, 我去Unblock youku的option按Test的話就說server有問題(Test failed! Perhaps the server isn't working properly.)
去搜狐也是連接有問題~說什麼"视频加载失败，请检查您的网络连接情况后重试，向我们留言反馈"
youku也是說什麼加载失败
不開Unblock youku就變回"亲爱的用户，该视频仅授权中国大陆地区用户观看，向我们留言反馈"

Unblock youku我已經用好久了…雖然偶爾比較慢…but most of the time does the job...hope you guys can get it fix soon.....thx for providing this free service the whole time, really appreciated. And whoever attacking the server is really an axxhole. 

By the way, 我是上網搜才找到你們的. 還有就是從這幾天起,就不斷搜到有人發什麼 Unblock youku現在改名成為 unblockcn....說不定是這些人斡的…well but who knowns…anyway你們加油吧. 支持你們,可以的話,請告訴我怎麼donation. 雖然不多, but i still would like to contribute. 
Unblockcn 的那些謠言:
https://www.google.com.au/search?q=UnblockCN&oq=UnblockCN&aqs=chrome..69i57j69i59j69i61&sourceid=chrome&es_sm=122&ie=UTF-8#q=UnblockCN&safe=off&start=10

**Comment by whuhacker** [comment]
@adamchan1023  感谢，我也注意到了这个情况，说不定就是他们攻击的。
我们正在加紧修复中……

**Comment by gaosong2101** [comment]
@adamchan1023 我也是在澳大利亚，在Chrome浏览器的扩展还是正常的，只不过视频刚开始的加载速度明显比以前慢。
PS：那些谣言真恶心人……

**Comment by tangdami** [comment]
chrome, iPad, Nexus 6 用各个pac也没办法看视频……好几天没看视频了……

**Comment by xiaoke11** [comment]
其实火狐可以手动换代理 只是很卡 直接google china proxies list 随便找一个 放 setting-advance-network 就可以了 手机同理 但很麻烦 不过大多数卡的要命 需要视频进入缓冲后关闭代理

**Comment by w09351500** [comment]
PC 端老老實實使用 Chrome 版本吧，不僅可以連線成功而且速度快得飛起。現在的問題是移動端沒有辦法解決連線的問題，伺服器被 DDoS 了。

我一直在想，既然 Chrome 版本的 Unblock Youku 可以正常運作，為什麼就沒有辦法連線至 Chrome
版本的伺服器呢？本人萌新，妄求各路大神說一下………
2015年8月4日 上午12:47於 "xiaoke11" <notifications@github.com>寫道：

**Comment by thomastian1993** [comment]
看了unblockcn 的介绍，就是7月开发出来的，打着解锁的幌子搞充值平台盈利，简直看不下去，感觉就应该是他们在攻击，有什么方法举报他们吗。

**Comment by RogerFederer03** [comment]
我试了一下，现在还是用不了，看来服务器还在被 DDoS ？

<img width="868" alt="screenshot 2015-08-03 21 03 04" src="https://cloud.githubusercontent.com/assets/5633006/9051030/3ee34d4c-3a23-11e5-87c5-05d5d77ee1d5.png">

**Comment by tommyzhaozbh** [comment]
免费的东西就有人喜欢抄袭，不支持原版却喜欢搬人家的东西，真是悲哀。难怪贴吧签到助手的作者都要放弃了。还真不排除是有人为了迫使大家用他的东西而把服务器炸了。难道我们就真的没有办法对付他们了吗?其实还真的挺期盼dns教程呢

**Comment by jasonyeo94** [comment]
我也觉得是unblock cn搞鬼~我有用其实也还好~unblock youku差的状态都比他好~还有就是除了土豆缓冲比较顺以为，爱奇艺有点卡~还说我网速卡~干！还是网速正常情况下~说什么加速器也没什么效果（土豆例外）~还是unblock youku好~

**Comment by jasonyeo94** [comment]
干~unblock cn我还注册了会员，都没公告什么的一些基本教学咨询都找不到~个人中心还有订单什么的项目~干~想删掉账号删不掉~
![untitled](https://cloud.githubusercontent.com/assets/13635098/9052468/72ef28b4-3a9a-11e5-8a5b-3b57d925e979.png)

**Comment by csyangning** [comment]
求教程 愿意自己出钱再嫁个服务器 也比被那个unblockcn骗钱的好

**Comment by jasonyeo94** [comment]
@csyangning 对啊~也许他们（unblockcn）想到了这个财路才强制终止/攻击他人的插件运作~

**Comment by Coyoter** [comment]
根本垃圾啊這Unblockcn。我寧可捐錢給Unblock youku也不要它們賺半毛錢。

**Comment by zhuzhuor** [comment]
@RogerFederer03 可以在 http://status.uku.im 查看最新的状态，鼠标移到图标上还可以看每天的 downtime/uptime
@tangdami Chrome 的代理服务器我正在弄，PAC 的服务器已经交给 @whuhacker 来管理了，估计他这两天就能弄好吧

**Comment by RogerFederer03** [comment]
好的，谢谢回复哈，希望早日弄好 @zhuzhuor

**Comment by r-learner** [comment]
unblock dns还是那个192.＊.＊.103？好像还是被ddos,sohu的视频还是看不了。

**Comment by gaosong2101** [comment]
我挂那个dns浏览网页会提示service unavailable，估计是dns没挂但是代理服务器挂了

**Comment by tywtyw2002** [comment]
对于DDOS 攻击目前基本上没有很好的办法去解决，目前我们有能力去做的只有尽一切可能的去减少中国服务器的压力，在外围设置level2 cache 服务器来做流量清洗。

如果攻击对手采用cc这样的手法去攻击，能做的只有限制ip连接数，但是这样又会影响NAT用户的体验。

对待DDOS的办法只有这样啦，不过最好的方式并不是抗DDOS，而是要敢于同unblock cn这样的人去抗衡。敢同恶鬼争高下不向霸王让寸分！

**Comment by willyansc** [comment]
你好，怎么用unblock dns啊，地址是什么？我老婆是你们的忠实用户，她看不了爱奇艺很着急。

**Comment by dougfresh9704** [comment]
http://status.uku.im/ 上面显示 unblock DNS is 100% up. How do I use that? Chrome is still down.... 刚买了腾讯好莱坞会员想看Game of Thrones却看不了了。。。呜呜

**Comment by zhuzhuor** [comment]
@dougfresh9704 抱歉，DNS 需要 `Proxy at Meituan Beijing (by @karlcheong) ` 配合才能使用

**Comment by adamchan1023** [comment]
真的,寧可捐錢給Unblock youku. 這件事沒發生之前我也沒想過要捐錢. 現在DNS被攻擊,好多天不能用了.讓我有點想報答一下Unblock youku的感覺. 這些年來一真提被這插件照顧了. 我本人對網絡設置其實也不太了解,記得我用unblock youku之前,是自己在網上找免費vpn,然後看了網上教學,設一堆東西才能用.也用過設置proxy什麼的…後來發現了這個chrome插件,就沒有再設了.現在unblock youku不能用了,我真心累了也不再像以前那樣搞一堆了.unblock youku好在,就是一個插件,我什麼都不用搞,簡單運作.就能上sohu,youku.什麼的看視頻. 所以如果捐錢能支持你們,我又不用搞這麼多東西,安裝一堆不知道安不安全的軟件…我真心寧可捐錢給你們…

@Coyoter 
就是…寧可損錢…也不想幾unblockun賺半毛錢
@csyangning 
我看到unblockcn好像要裝什麼的,所以我就不想用了…也不知道信不信得過…不想被騙…所以不想用
@gaosong2101 
他們好像也有人Post在yeeyi…真的很惡心....unblockyouku用不了…真的有點難過
@jasonyeo94 
還有人一直跑到各地海外討論區發文…名號是什麼candy....我搜的時候看到的
所以說不定真的是unblockcn....一開始還以為是真的…搜到這個網才知道是假的…
真的很討人厭…

**Comment by leungwf** [comment]
@adamchan1023 同意捐錢!用了好幾年unblock youku了!一直都很穩定!絕不能給這流氓搞垮 @zhuzhuor 讓大家一起出點力

**Comment by jasonyeo94** [comment]
@adamchan1023 unblock cn的確是需要下載他們的軟體還有好像只提供免費到8月30號（沒記錯的話）~
看圖吧~
![untitled](https://cloud.githubusercontent.com/assets/13635098/9084312/f1444ae0-3ba4-11e5-96d8-60ee10005f28.png)

**Comment by alexking99** [comment]
@zhuzhuor dns好像是恢復正常了 沒顯示只限內地了 是不是?

**Comment by w09351500** [comment]
Pac 也已經恢復正常，天祐 UY，別讓 UYC 有機可趁
2015年8月5日 下午7:40於 "alexking99" <notifications@github.com>寫道：

**Comment by fiveinches** [comment]
@w09351500 pac有恢复么 我的还是不可以啊

**Comment by gaosong2101** [comment]
http://status.uku.im/
看这个好像是两个阿里云的都上线了，恭喜，撒花~~~~~~~~~~~
还有一个美团云的还没恢复，不过我估计也快了吧，加油(•̀ロ•́)و✧ ~~

**Comment by zhuzhuor** [comment]
@alexking99 @w09351500 @fiveinches @gaosong2101 
DNS 已经刚刚被 @whuhacker 修复了，大家用用看看情况
PAC 文件用的代理服务器还是时好时坏，等等修复吧

**Comment by gaosong2101** [comment]
辛苦啦，非常感谢

**Comment by alexking99** [comment]
@zhuzhuor 請問 在pc上hosts改dns 是不是也支持 pc 端?

**Comment by thomastian1993** [comment]
是的，同意捐钱，或者我们可以自己学架设dns

**Comment by w09351500** [comment]
我錯了，PAC 一樣無法運行，可以運行的只有 DNS     T.T

**Comment by tangdami** [comment]
目前在iOS上用DNS能看所有视频app了～～Android上也能看bilibili了，好感动……各位大神加油啊！！

**Comment by fiveinches** [comment]
@tangdami 请问你说的ios是只电脑么 还是iphone ipad都可以 请问dns怎么设置呢

**Comment by tangdami** [comment]
@fiveinches 电脑那个叫 Mac OS 😅😅 我用的 iPad。在WiFi里面填写 192.241.222.103

**Comment by w09351500** [comment]
@tangdami 同，即使高清的跑不動，能跑順暢我就已經很滿足了，寧死也不服從 UnblockCN。

**Comment by tangdami** [comment]
@w09351500 我在加拿大，开各种视频app的超清都很流畅，满足了…

**Comment by w09351500** [comment]
@tangdami 估計台灣線路質量不行，唉

**Comment by fiveinches** [comment]
@tangdami 我的ipad设置之后依然不行...

**Comment by zhuzhuor** [comment]
@fiveinches 填在 DNS 的那一行了吗，另外 app 有时候可能有缓存，你[把 app 整个 kill 掉](https://support.apple.com/en-us/HT201330) 再试试
@w09351500 我们现在想了一些办法来抵御这些攻击，我个人的感觉是各个服务都是慢慢恢复中，请再耐心等等

**Comment by fiveinches** [comment]
@zhuzhuor 嗯 填在那一行了 我去那个是ip的网址 试完依旧是false

**Comment by fiveinches** [comment]
@zhuzhuor 刚重新弄了一下 可以使用了 辛苦了

**Comment by zhuzhuor** [comment]
通过这次被人恶意宣传的事情，深深地感受到了话语权的重要性。这被人诽谤中伤也没有办法反驳，感觉太不好了。我之前还觉得我们这个软件要做的低调一点才能更长久地服务用户，但是这样用户被诱导被骗更不是我们想要的

于是这次我去注册了 Twitter 和 Weibo 的官方帐号，再加上个之前注册的 facebook 主页，用来好好地给用户发布消息、通知、更新，以及抵抗这种恶意宣传
**欢迎大家去关注和转发**，回头我也把这几个网址加在扩展程序里让大家都能看到

* Weibo http://weibo.com/ubuku
* Facebook https://www.facebook.com/pages/Unblock-Youku/597420297038895
* Twitter 稍后贴链接

这三百万用户的安全是我们最重要的事情，之前出现过很多个用我们的开源程序改一改[换个名字来窃取用户隐私的例子](https://github.com/zhuzhuor/malicious-chrome-extensions)。这次这个 UnblockCN  是个比 Chrome 扩展的权限更高的桌面软件，从现在这大力的恶意宣传上来看也不是什么好玩意，不知道回头还会做出什么事情来，我们要坚决抵制

**Comment by fiveinches** [comment]
@zhuzhuor 已关注微博 如果捐款发起的话 请及时通知 很愿意为unblock youku出一份力

**Comment by zhuzhuor** [comment]
@fiveinches 谢谢！

**Comment by zhuzhuor** [comment]
Twitter 账户的链接也贴上了，欢迎 follow 和 retweet

**Comment by gaosong2101** [comment]
已关注+转推

**Comment by tangdami** [comment]
同已经关注+转推！！必须要曝光ub cn的恶心行为！

**Comment by gaosong2101** [comment]
我觉得在具体是谁攻击的明确知道之前还是不要总是怀疑unblockcn，只能说是有可能是他们....
不过他们的宣传方法真是够恶心人的、

**Comment by zhuzhuor** [comment]
微博刚才第一次发的消息好像被新浪微博当做 spam 屏蔽了，只有我自己能看到，别人都看不到
刚刚又重发了一遍，欢迎大家转发

**Comment by gaosong2101** [comment]
建议申v

**Comment by zhuzhuor** [comment]
今天貌似攻击消停了，前一段时间总是北京时间早上八点准时开始攻击
现在应该扩展程序、PAC 文件、DNS 都基本上接近正常工作了，可以再观望观望

@gaosong2101 橙 v 好像只能给个人用户，企业蓝 v 得营业执照 + $1000 申请费...

**Comment by zhuzhuor** [comment]
最近为了抵御 DDoS 攻击，增加了很多后台的服务器，刚刚一并都加到 public status page 了
最新的服务器状态请看 http://status.uku.im/

**Comment by gaosong2101** [comment]
.....我去 原来还免费来着 （新浪这是彻底坑不到钱只好从这里压榨了嘛hhhhh）

**Comment by xin-zhang** [comment]
:+1:

**Comment by tommyzhaozbh** [comment]
辛苦了，不过这样大量添加服务器会不会成本大增呢？

**Comment by whuhacker** [comment]
@tommyzhaozbh 暂时保证 Unblock Youku 的用户能正常使用吧，对于恶意 DDoS 攻击坚决抗争。成本我们可以先自己承担。

**Comment by Coyoter** [comment]
決定傍晚幫你們報導這件事！

**Comment by jasonyeo94** [comment]
服务器最少也要5-10万以上吧？

**Comment by zyy218** [comment]
我在香港，加了yo.uku.im/proxy.pac，但有些电影还是受地区限制，是这样吗？求大侠帮忙，以前都可以看的。

**Comment by alexking99** [comment]
@zyy218  http://status.uku.im/  pac文件被下線 看一看狀態

**Comment by w09351500** [comment]
DNS 伺服器是不是不太穩定了？昨日可以連，今日又連不上了

**Comment by zhuzhuor** [comment]
@w09351500 今天 DNS 的确又有点问题，明天看 @whuhacker 修修吧
@zyy218 刚才 PAC 的代理服务器也有点问题，现在临时修复了一下，等回头迁移到更稳定的服务器上吧

**Comment by w09351500** [comment]
@zhuzhuor 請問目前的 PAC 的地址是 yo.uku.im 還是 dns. umbridges2014.com？還是說兩個都行？

**Comment by zhuzhuor** [comment]
@w09351500 是 `http://pac.uku.im/pac.pac`

**Comment by w09351500** [comment]
驚了，原來 PAC 地址是這個，我看版上的帖子都是我說的那兩個，遭不住了
2015年8月7日 上午3:10於 "Bo Zhu" <notifications@github.com>寫道：

**Comment by bobwongwong** [comment]
Unblockcn那家伙的服务器也挂了 哈哈哈 是你们干的吗？ 爽 就应该这样 加油

**Comment by jasonyeo94** [comment]
@bobwongwong  Unblockcn服务器挂了应该是他们自己的问题吧~~~~就算不挂以后也需付费~

**Comment by tommyzhaozbh** [comment]
怎么回事儿?所有服务器又瘫痪了

**Comment by tommyzhaozbh** [comment]
嗬，又没事了。看来服务器偶尔还会发脾气的…

**Comment by jasonyeo94** [comment]
@tommyzhaozbh  哈哈~不好吓我哦~我还想看无限挑战的~哈哈~

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 没事，这次不是攻击
因为 pingdom 不能直接检测代理服务器，所以其实我写了个 heroku 的 app 来帮忙检查，pingdom 显示的是这个 app 的检查结果
刚才我 update 了下 heroku 的 app，还没来得及改 pingdom 的设置，于是就全线爆红了一下。话说 pingdom 的这 status 展示还挺灵敏的

**Comment by tommyzhaozbh** [comment]
@jasonyeo94 我还想看running man呢，不过我最需要的还是听歌~
@zhuzhuor 吓一跳啊真是，我每天都会检查好几次的。另外能把firefox的服务器加进列表去么?还有dns好像还没行

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 刚才问了下 @whuhacker，Firefox 的扩展还是用的 `http://pac.uku.im/pac.pac` 里面的代理服务器，所以看 `PAC proxy server` 这个状态就行
Firefox 已经支持 HTTPS 代理了，@whuhacker 说他之后改成和 Chrome 扩展用一样的服务器

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 另外 DNS 用的代理服务器也貌似刚被 @whuhacker 修复，可以试试看

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 感谢，辛苦了。还有我问一下自己搭建的服务器怎么更新url list?自己手动还是?

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 我之前写个脚本自动更新 URL 列表，等我整理一下放出来吧。在那之前可以试试手动更新。不过最近 URL 更新不是那么频繁，应该不更新也能用上一阵子了

**Comment by jasonyeo94** [comment]
@tommyzhaozbh  running man我看了~听歌？你都听什么的？bigbang的歌你有听吗？新歌不错~

**Comment by tommyzhaozbh** [comment]
@jasonyeo94 Bigbang 的比较少听，我听的基本都是女团的，少时的、Apink的、EXID的都有。看的综艺很多呢，除了RM还有我结、非首脑、真男和小电视^_^

**Comment by Kanaeva** [comment]
zhuzhuor>
想请问下zhuzhuor老大，现在的DNS是否还是192.2xx.2xx.103以及128.1xx.1xx.223这个呢? 最近不能用上来看看原来是被攻击了，但是读了昨天有人说可以，不过小弟用手机尝试看乐视apps视频依然显示只支持中国用户等信息... 如果DNS换了可否告知新的地址? 谢谢 !!

**Comment by tommyzhaozbh** [comment]
@Kanaeva DNS服务器还是192.241.222.103

**Comment by jasonyeo94** [comment]
@tommyzhaozbh  女团~我也有听一些，可是比较sistar~

**Comment by fiveinches** [comment]
@zhuzhuor 我想问下之前用pac 可以听qq音乐 这次修复之后qq音乐听不了了 是什么原因呢

**Comment by hihitoni** [comment]
使用pac QQ音乐听不了 我用的的是路由器 dns就可以

**Comment by zhuzhuor** [comment]
@fiveinches 我不太确定这个问题所在，PAC 用的代理服务器是我这两天临时搭的，现在已经交给 @whuhacker 维护了。你用 Chrome 或者 Firefox 的扩展程序可以用吗

@hihitoni 多谢反馈！

**Comment by Sissssssy** [comment]
腾讯视频也终于看不了了，youku是早就不能看了。
然后腾讯视频有一个申告ip地址是否正确的链接，点进去为什么显示是辽宁的ip？
您当前的IP为：139.196.18.201
该IP所在地为：中国辽宁省阜新市 阿里巴巴

so。。。不能用还是因为受到攻击的原因吗？

**Comment by zhuzhuor** [comment]
@Sissssssy 优酷和腾讯都不能看吗？你所住的地区是？
刚刚也有别人报告腾讯的问题 https://github.com/zhuzhuor/Unblock-Youku/issues/457，关于腾讯的问题就到那里去讨论吧

**Comment by zhuzhuor** [comment]
这两天应该是没有 DDoS 攻击了，各个服务器也趋于正常了，这个 issue 就 close 了
有新的问题可以再开新的 issue https://github.com/zhuzhuor/Unblock-Youku/issues/new

**Comment by Candiexu** [comment]
大神们，请问什么时候UNBLOCK YOUKU可以恢复正常啊？

**Comment by Candiexu** [comment]
我在加拿大，看优酷显示的是 ---- 错误代码 2003， 这是什么意思啊？ 谢谢了

**Comment by zhuzhuor** [comment]
@garydevil 我们最近增加了几台服务器，达到 pingdom 的服务器监控数量上限了，于是换了别家的服务
新的 status report 页面可以访问 https://status.uku.im

**Comment by garydevil** [comment]
zhuzhuor  3q3q ^^^
