### ISSUE TITLE
腾讯视频挂了

### ISSUE THREAD

**Issue by leonqi4rdm** [zhuzhuor/Unblock-Youku#454]
今早开腾讯视频，显示
![image](https://cloud.githubusercontent.com/assets/3901082/8986387/fd97fb2a-36a9-11e5-8a4d-288f7db8730f.png)
好莱坞影院在firefox里更显示
![image](https://cloud.githubusercontent.com/assets/3901082/8986427/25fb54fe-36aa-11e5-9368-6228b68bd6fa.png)

**Comment by zhuzhuor** [comment]
见 https://github.com/zhuzhuor/Unblock-Youku/issues/452

**Comment by leonqi4rdm** [comment]
:+1:
