### ISSUE TITLE
Bilibili 究竟出了什麼問題？

### ISSUE THREAD

**Issue by w09351500** [zhuzhuor/Unblock-Youku#455]
Firefox 的 Unblock Youku 差不多在兩三天前就已經失效，目前是使用 Chrome 的才能正常瀏覽正版動畫。

在行動裝置上面，Bilibili 一直是封鎖海外 IP 的瀏覽正版動畫的，但是我們可以使用 DNS 或是 Pac 突破，Pac 剛剛得知已經重新開啟？(鏡像伺服器)，可是 Bilibili 一樣是無法瀏覽的，不曉得是我設置的不對還是 Bilibili 的問題？

我用的是 Drony，地址是 http://yo.uku.im/proxy.pac

只是我也懷疑 Drony 1.2.89 貌似有些問題，第一次更新的時候就曾經出現無法使用的情形………困擾中，或求個可以在 Bilibili 行動裝置版正常瀏覽正版動畫的方法。

**Comment by yihuigu** [comment]
Bilibili 用DNS可以看。




On Thu, Jul 30, 2015 at 5:24 PM -0700, "w09351500" <notifications@github.com> wrote:












Firefox 的 Unblock Youku 差不多在兩三天前就已經失效，目前是使用 Chrome 的才能正常瀏覽正版動畫。



在行動裝置上面，Bilibili 一直是封鎖海外 IP 的瀏覽正版動畫的，但是我們可以使用 DNS 或是 Pac 突破，Pac 剛剛得知已經重新開啟？(鏡像伺服器)，可是 Bilibili 一樣是無法瀏覽的，不曉得是我設置的不對還是 Bilibili 的問題？



我用的是 Drony，地址是 http://yo.uku.im/proxy.pac



只是我也懷疑 Drony 1.2.89 貌似有些問題，第一次更新的時候就曾經出現無法使用的情形………困擾中，或求個可以在 Bilibili 行動裝置版正常瀏覽正版動畫的方法。

**Comment by w09351500** [comment]
DNS 的設置我一直不太明白

因為我沒有 Root，只能使用 Wifi 進行修改，我在 DNS1 欄位上面 Key 上 192.241.222.103 後仍舊無法正常打開正版動畫，還是說我哪個操作環節失誤了？

**Comment by yihuigu** [comment]
DNS好像目前被攻击，我也看不了。




On Thu, Jul 30, 2015 at 5:38 PM -0700, "w09351500" <notifications@github.com> wrote:












DNS 的設置我一直不太明白



因為我沒有 Root，只能使用 Wifi 進行修改，我在 DNS1 欄位上面 Key 上 192.241.222.103 後仍舊無法正常打開正版動畫，還是說我哪個操作環節失誤了？

**Comment by w09351500** [comment]
說也奇怪，Chrome 的 UY 若不開啟，不要說 BiliBili 正版動畫，就連「獨家正版」字樣的都無法開啟。

問題在於行動裝置版的 Bilibili 無須 DNS 或是 Pac 就能直接開啟有「獨家正版」字樣的動畫，我也是醉了 2333

**Comment by zhuzhuor** [comment]
@w09351500 貌似 PAC 的镜像服务器现在也被攻击了，估计只能等等了

**Comment by zhuzhuor** [comment]
相关的讨论都集中在 https://github.com/zhuzhuor/Unblock-Youku/issues/453 吧，这个 issue 就先关闭了

**Comment by zhuzhuor** [comment]
给错 link 了，是这个 issue https://github.com/zhuzhuor/Unblock-Youku/issues/452

**Comment by tangdami** [comment]
现在 Android 5.x 支持wifi上面添加PAC了，按照楼主说的，能在上面填上那个DNS的PAC来使用bilibili的app吗？？我试了一下DNS的也是不行，打开视频都是提示连接失败……其他非正版的和独家的反而能看

**Comment by w09351500** [comment]
BiliBili 正版動畫在 Unblock Youku 被攻擊後，無論是 DNS 或是 PAC 都無法觀看…

只是我很納悶，PC 端必須使用 Unnlock Youku(Chrome 版本) 才能觀看獨家正版的動畫，但是移動端卻不用，莫非移動端自帶代理了？
2015年8月4日 上午12:42於 "tangdami" <notifications@github.com>寫道：

**Comment by tangdami** [comment]
@w09351500 我刚在PC的 chrome上面试了，配合chrome的unblock youku插件，在bilibili上面看独家正版、最近的新番，都能流畅观看。
就是Android版的不知道怎么弄，所有正版、新番都看不了，加载不了视频链接。我的Nexus 6 with 5.1.1设置：
wifi里面填上 DNS 的PAC，bilibili的Android app里面把“海外用户加速”功能关掉，无法观看独家正版。
