### ISSUE TITLE
騰訊視頻不能看 昨天還好好的

### ISSUE THREAD

**Issue by MalachaiParker** [zhuzhuor/Unblock-Youku#457]
http://v.qq.com/cover/q/qviv9yyjn83eyfu/b0017amtuli.html
各種劇阿 都會出現"根據您的ip地址，因該地區不在版權授權區內...等"
土豆 youku等 都可以 就騰訊不行
裝的是chrome的unblock youku插件 三種模式都不行

http://status.uku.im/
上面這個狀態我不太會看= = 不好意思 不知道哪個是哪個 

之前幫我媽媽用的都是直接改ie的這個 http://yo.uku.im/proxy.pac 前幾天突然不能用了
昨天幫他裝了chrome的插件 昨天還能看 今天就不能看了
老人家嘛 甚麼也不懂 弄得好像都是我搞得才能看 一直煩我 快被他氣炸了...

另外有看到http://pac.uku.im/pac.pac 等等試試看..

**Comment by MalachaiParker** [comment]
用了http://pac.uku.im/pac.pac 
check之後出現true,突然覺得充滿希望 
但騰訊還是不能看 其他土豆 優庫什麼的都可~
我媽媽只會用騰訊....

**Comment by zhuzhuor** [comment]
@MalachaiParker 刚才用 Chrome 和 Firefox 试了下，我这里都还是可以看的
你所在的城市/地区是什么？

实在不行，Chrome 试试在 chrome://extensions 页面删掉扩展程序，然后去 http://uku.im/chrome 重装一下

**Comment by MalachaiParker** [comment]
@zhuzhuor 
台灣
重裝蠻多次的 都不行~~
只有騰訊不能 其他都能 所以覺得納悶 QAQ

**Comment by MalachaiParker** [comment]
而且騰訊上都寫說 偵測到我的ip所在地 是中国辽宁省阜新市 阿里巴巴 

還不給看 真奇怪

**Comment by zhuzhuor** [comment]
@MalachaiParker 你这个比较奇怪
之前有澳门的用户遇到奇怪的问题 https://github.com/zhuzhuor/Unblock-Youku/issues/64

你试着改成 Google 的 DNS 看看 https://developers.google.com/speed/public-dns/

**Comment by benhong** [comment]
@zhuzhuor pac 档的规则好像没有
http://aid.video.qq.com/fcgi-bin/userip?otype=json
有些视频会用这个网址检测ip

**Comment by MalachaiParker** [comment]
@zhuzhuor 
試過改成 google 的 dns 了 沒起作用

**Comment by MalachaiParker** [comment]
![111](https://cloud.githubusercontent.com/assets/13693760/9140212/06bc6cc2-3d62-11e5-872b-527545a68ee6.PNG)

**Comment by MalachaiParker** [comment]
#458 遇到的 跟這位貼的圖一樣
然後
如果沒開unblock youku 點糾正 出現的ip位置就是"台灣"的
如果開了unblock youku 點糾正 出現的ip位置就是"中国"辽宁省阜新市 阿里巴巴
代表有起作用吧 但卻不給看 真是奇怪=__=

**Comment by benhong** [comment]
@MalachaiParker  出現的ip位置就是"中国辽宁省阜新市 阿里巴巴"
并不表示可以通过，要是我没记错的话
验证ip好像会分成2关

第一关是一进去就侦测
第2关 是在取的影片的相关讯息才会侦测
当取的影片的相关讯息时，要是大陆的ip 他就会返回真的内容
要是非大陆的ip 他会返回 拒绝的内容

你可以尝试这样抓出网址
1.先到汇出错的视频网页
2.开启 Chrome  按下f12 会出现debug 的视窗
2.在debug 的视窗选择network
3.在filter 的栏位 填上  getv
4.应该会出现 getvinfo 或  getvkey
5.在关键字的下面会写是网址 例如 vv.video.qq.com (大概会变动的就是vv了)
6.再来回报 你所看到的网址，我们在分析是否已经有在 chrome 扩展内

**Comment by MalachaiParker** [comment]
![default](https://cloud.githubusercontent.com/assets/13693760/9141598/88728fda-3d6c-11e5-892f-5fa40f41682c.PNG)
是這個嗎..

**Comment by ahzuo** [comment]
@zhuzhuor @MalachaiParker :"limit"字眼是被限制？？但地区确实是中国境内
![untitled3](https://cloud.githubusercontent.com/assets/13696622/9142196/ba4248b2-3d70-11e5-8bbf-09d76f5bceaf.jpg)

**Comment by benhong** [comment]
@ahzuo 那个网址验证是第一关
在@MalachaiParker  说明了是卡在 getvinfo 那关

这边有解释原因 #458

**Comment by zhuzhuor** [comment]
问题应该已经修复了，大家可以重新试一下
如果有问题再来来回复，多谢反馈！

**Comment by MalachaiParker** [comment]
已經可以看了 謝謝作者^^
