### ISSUE TITLE
QQ腾讯视频看不了

### ISSUE THREAD

**Issue by ahzuo** [zhuzhuor/Unblock-Youku#458]
除了腾讯，其他在线视频网站Unblock Youku都能正常运行其功能。我已重新安装了Unblock Youku甚至整个Google Chrome游览器，但始终不行。我这个问题与他一样#457，请@zhuzhuor尽快处理，感恩。
![untitled](https://cloud.githubusercontent.com/assets/13696622/9139946/1cd1f920-3d60-11e5-922e-8ee81c3e4e58.jpg)

**Comment by benhong** [comment]
给作者，把这台伺服器换个ip吧


Remote Address:106.184.5.139:993
Request URL:http://vv.video.qq.com/getvinfo
Request Method:POST
Status Code:200 OK

<root><em>80</em><exem>1</exem><exinfo>日本--</exinfo><exmsg>IP limit</exmsg><msg>ip is not authorized</msg><s>f</s></root>

IP 被误判成 日本了......
跟我的 代理伺服器一样 都被误判成日本真他们有够无言的

**Comment by MalachaiParker** [comment]
![default](https://cloud.githubusercontent.com/assets/13693760/9141671/067fd1da-3d6d-11e5-9319-de3810224264.PNG)

**Comment by ahzuo** [comment]
怎么会变成这样呢~真是奇怪~话说我前几天还能正常使用Unblock Youku~希望问题能尽快解决
![untitled2](https://cloud.githubusercontent.com/assets/13696622/9141900/b6b12e18-3d6e-11e5-8aeb-2b1dc4580104.jpg)

**Comment by MalachaiParker** [comment]
![default](https://cloud.githubusercontent.com/assets/13693760/9141927/f12592b4-3d6e-11e5-84b3-713eb003e9b5.PNG)

**Comment by ahzuo** [comment]
怎么会变成这样呢~真奇怪~话说前几天我还能正常使用Unblock Youku~希望能解决恢复
![untitled2](https://cloud.githubusercontent.com/assets/13696622/9141938/1691d4d6-3d6f-11e5-84e4-5910b4e3a957.jpg)

**Comment by zhuzhuor** [comment]
@MalachaiParker @benhong 你们是在哪看到这个显示日本的信息的？
我这里用 @MalachaiParker 提供的那个视频链接，一直都没办法重现这个问题... 有点尴尬

**Comment by benhong** [comment]
@zhuzhuor 来这里
http://v.qq.com/cover/o/ouwrkn72batk58k.html?vid=r0017q277xa
看 Request URL:http://vv.video.qq.com/getvinfo
他的返回直 就会说是 日本的 
![image](https://cloud.githubusercontent.com/assets/13610597/9143262/d8cccc60-3d77-11e5-8527-59e9bf75e3f9.png)

**Comment by zhuzhuor** [comment]
@benhong OK 感谢... 我这里也能重现了

**Comment by benhong** [comment]
@zhuzhuor  我买美团云主机呀，ip都不能看腾讯
因为我世新注册的用户，只能买北京3区，
是否可以推荐其他加的云主机呀

**Comment by zhuzhuor** [comment]
我大概找到这个问题的症结所在了，是我们的服务器的配置原因，应该不是腾讯的问题
等我问问别人，稍微 research 一下，看看这个配置怎么修改比较好

@benhong 国内的比较靠谱的服务器我就用过 aliyun 和 美团云
还有一些没用过的例如 ucloud.cn 特别贵
还有个 360 云主机，网页上连价格都没标，不知道会不会被坑

**Comment by benhong** [comment]
@zhuzhuor 你不是说aliyun 要先备案嘛？？？
看来我只能去ㄠ客服了，请他让我买北京1区的云主机

**Comment by zhuzhuor** [comment]
@benhong 恩，aliyun 要么备案要么用 TLS，都比较麻烦
你可以让他们给你换个 IP 试试，说不定只是个别 IP 的问题

**Comment by zhuzhuor** [comment]
问题应该已经修复了，大家可以重新试一下
如果有问题再来来回复，多谢反馈！

**Comment by MalachaiParker** [comment]
@zhuzhuor 恩恩 已經可以看了 謝謝作者^^

**Comment by carilwang** [comment]
在小米盒子里面，把dns改成那个了，还是不能看腾讯与优酷的

**Comment by zhuzhuor** [comment]
@carilwang DNS 的问题得问问 @whuhacker

**Comment by ahzuo** [comment]
可以正常看腾讯视频了，谢谢各位，希望Unblock Youku越来越好。
