### ISSUE TITLE
關於Firefox版的更新和捐款問題

### ISSUE THREAD

**Issue by kbboss7416** [zhuzhuor/Unblock-Youku#459]
各位好，最近因為不能在firefox上看bilibili的動畫才找到這裡。先感謝各位開發者的用心，我本人不是電腦相關技術人員，所以只能默默支持並感謝作者的苦心，讓許多使用者都能受益。

我想請教一下，FireFox版的更新何時有可能完成?(本人不太用Chrome)，之前翻了一下文章，好像FireFox的版本失效了，我個人用起來的感覺也是如此，所以希望能儘快恢復正常的使用功能。

另外雖然我不能幫上實質的技術改善層面的問題，但至少還能捐一點錢幫助整個項目的持續運作，所以希望能儘快公布捐款的機制，我也有訂閱FB專頁，如果能在FB上發布相關的捐款訊息的話，那就太好了。因為我住在台灣，所以希望未來捐款的方式也能讓台灣這裡的使用者能順利使用，謝謝!

**Comment by zhuzhuor** [comment]
Firefox 版的现在应该也能用了，你可以试试
如果回头开始接受捐款了，一定会在各个 social network 上通知的，非常感谢！

我们最近也开设了别的 social network 账户，欢迎关注
