### ISSUE TITLE
關於自架Unblock服務器

### ISSUE THREAD

**Issue by BensonYu** [zhuzhuor/Unblock-Youku#470]
Hi，
我剛剛用Raspberry pi 2微板建了一個TVBOX(OSMC), 上網看到一些文章說可以用ub.uku.js自建一個服務器？請問ub.uku.js這個文件在哪裡下載的？我看了下源碼沒找到...另外是不是要用node.js來運行？

聽說我將這個跑起來後，家裡所有的設備(Apple, Android, PC)都能指向這個代理訪問中國網站的？ XD

**Comment by zhuzhuor** [comment]
ub.uku.js 这个已经废弃了
现在你需要找一个中国大陆的代理服务器才行
更多的信息你可以看看 #453，可以在那里讨论，这个 issue 就关闭了

**Comment by BensonYu** [comment]
Okay, 謝謝，我去參考一下#453
