### ISSUE TITLE
python不能连接

### ISSUE THREAD

**Issue by carilwang** [zhuzhuor/Unblock-Youku#471]
我写了个python的script但是会出现exception,想问问是不是需要一些权限的东西
c = requests.get('http://ipservice.163.com/isFromMainland', proxies={'https': 'https://proxy.uku.im:443','http': 'https://proxy.uku.im:443'})
    print c.content
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='proxy.uku.im', port=443): Max retries exceeded with url: http://ipservice.163.com/isFromMainland (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 403 Forbidden',)))

不太懂squid的东西

**Comment by zhuzhuor** [comment]
应该是个 http 的代理，不是 https 的，你试试看
另外 proxy.uku.im 最近刚交给 @tywtyw2002 来管理了，他可能已经/将来加 access control 的东西吧

**Comment by tywtyw2002** [comment]
没有问题呀
```
tyw@CosHiM-MAC:~|⇒  curl -x http://proxy.uku.im:443 http://ipservice.163.com/isFromMainland
true% 
```

这个机器没有https， 用http协议端口 443

**Comment by carilwang** [comment]
明白了。谢谢大家
