### ISSUE TITLE
爱奇艺龙珠超已经瘫了，摆脱修复一下，谢谢

### ISSUE THREAD

**Issue by 511042189** [zhuzhuor/Unblock-Youku#474]
http://www.iqiyi.com/v_19rro6a0g4.html?vfm=2008_aldbd&bvfm=videolocal 根本看不起啊

**Comment by zhuzhuor** [comment]
我这里试还 OK
你能提供更具体的信息吗，比如别的网站上的视频可以看吗，你自己的国家地区，安装了别的什么扩展程序吗，你看到的错误提示是？

>  ![screen shot 2015-08-22 at 10 12 17 pm](https://cloud.githubusercontent.com/assets/928905/9427036/0240f518-491b-11e5-974c-35465ae0d8eb.png)

**Comment by 511042189** [comment]
谢谢，现在又好了，我之前就是能打开网站，但是视频栏都是黑的什么都没有，我在美国洛杉矶
